// ─── TerraIQ_WEB/src/lib/generateReport.js ────────────────────────────
// Generates a branded PDF report for soil analysis or scan results
// Uses html2canvas + jsPDF (add to package.json: npm install html2canvas jspdf)
// 
// USAGE:
//   import { generateSoilReport, generateScanReport } from "@/lib/generateReport";
//   await generateSoilReport({ params, result, farmerName, location });
//   await generateScanReport({ result, farmerName, location });

// ── Color palette (matches UI) ────────────────────────────────────────
export const PARAM_COLORS = {
  nitrogen:       { hex: "#3B82F6", name: "Nitrogen",       unit: "mg/kg" },
  phosphorus:     { hex: "#F59E0B", name: "Phosphorus",     unit: "mg/kg" },
  potassium:      { hex: "#F97316", name: "Potassium",      unit: "mg/kg" },
  ph:             { hex: "#8B5CF6", name: "pH Level",       unit: "" },
  organic_carbon: { hex: "#92400E", name: "Organic Carbon", unit: "%" },
  moisture:       { hex: "#06B6D4", name: "Moisture",       unit: "%" },
};

const SEVERITY_COLORS = {
  low:      "#22C55E",
  moderate: "#F59E0B",
  high:     "#F97316",
  critical: "#EF4444",
};

const RATING_COLORS = {
  excellent: "#16A34A",
  good:      "#22C55E",
  fair:      "#F59E0B",
  poor:      "#EF4444",
};

// ── Score to percentage bar ───────────────────────────────────────────
const SCORE_PCT = { 1: 15, 2: 35, 3: 65, 4: 90 };

function levelColor(level) {
  const reds    = ["critically_low","too_high","too_acidic","too_alkaline","waterlogged","critically_dry"];
  const oranges = ["low","acidic","dry"];
  const greens  = ["sufficient","optimal","adequate","moderate","high","very_high"];
  const yellows = ["slightly_alkaline","wet"];
  if (reds.includes(level))    return "#EF4444";
  if (oranges.includes(level)) return "#F97316";
  if (yellows.includes(level)) return "#EAB308";
  if (greens.includes(level))  return "#22C55E";
  return "#6B7280";
}

// ── Load jsPDF dynamically ────────────────────────────────────────────
async function loadJsPDF() {
  if (window._jspdf) return window._jspdf;
  const { jsPDF } = await import("jspdf");
  window._jspdf = jsPDF;
  return jsPDF;
}

// ── Draw watermark on every page ──────────────────────────────────────
function drawWatermark(doc, pageW, pageH) {
  doc.saveGraphicsState();
  doc.setGState(new doc.GState({ opacity: 0.07 }));
  doc.setFontSize(52);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 138, 76);
  doc.text("TerraIQ+", pageW / 2, pageH / 2, {
    align: "center",
    angle: 35,
  });
  doc.restoreGraphicsState();
}

// ── Draw page header ──────────────────────────────────────────────────
function drawHeader(doc, pageW, title, timestamp) {
  // Green header bar
  doc.setFillColor(30, 138, 76);
  doc.rect(0, 0, pageW, 22, "F");

  // TerraIQ+ logo text
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text("TerraIQ+", 14, 14);

  // Report title
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(title, pageW / 2, 14, { align: "center" });

  // Timestamp
  doc.setFontSize(7.5);
  doc.text(timestamp, pageW - 14, 14, { align: "right" });

  return 30; // y cursor after header
}

// ── Draw page footer ──────────────────────────────────────────────────
function drawFooter(doc, pageW, pageH, pageNum) {
  doc.setDrawColor(30, 138, 76);
  doc.setLineWidth(0.3);
  doc.line(14, pageH - 14, pageW - 14, pageH - 14);
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text("Generated by TerraIQ+ · Precision Agriculture for Nigerian Farmers", 14, pageH - 8);
  doc.text(`Page ${pageNum}`, pageW - 14, pageH - 8, { align: "right" });
}

// ── Draw a parameter bar ──────────────────────────────────────────────
function drawParamBar(doc, x, y, label, value, unit, cls, color, barW = 100) {
  const pct = cls ? (SCORE_PCT[cls.score] ?? 50) : 50;
  const barColor = cls ? levelColor(cls.level) : "#22C55E";
  const levelLabel = cls?.label ?? "";

  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 30, 30);
  doc.text(`${label}:`, x, y);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text(`${value}${unit}`, x + 38, y);

  // Badge
  const badgeColor = barColor;
  doc.setFillColor(...hexToRgb(badgeColor));
  doc.setDrawColor(...hexToRgb(badgeColor));
  doc.roundedRect(x + 58, y - 4.5, 28, 6, 1.5, 1.5, "F");
  doc.setFontSize(6.5);
  doc.setTextColor(255, 255, 255);
  doc.text(levelLabel, x + 72, y, { align: "center" });

  // Bar track
  doc.setFillColor(220, 220, 220);
  doc.roundedRect(x, y + 2.5, barW, 3.5, 1, 1, "F");

  // Bar fill
  doc.setFillColor(...hexToRgb(barColor));
  doc.roundedRect(x, y + 2.5, barW * pct / 100, 3.5, 1, 1, "F");

  // Color dot for legend
  doc.setFillColor(...hexToRgb(color));
  doc.circle(x - 5, y - 1, 1.5, "F");

  return y + 12;
}

function hexToRgb(hex) {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return [r, g, b];
}

// ── Section heading ───────────────────────────────────────────────────
function sectionHeading(doc, x, y, text, pageW) {
  doc.setFillColor(241, 247, 244);
  doc.rect(x, y - 5, pageW - x * 2, 9, "F");
  doc.setDrawColor(30, 138, 76);
  doc.setLineWidth(0.5);
  doc.line(x, y - 5, x, y + 4);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 138, 76);
  doc.text(text, x + 4, y);
  return y + 10;
}

// ── Wrapped text helper ───────────────────────────────────────────────
function wrappedText(doc, text, x, y, maxW, lineH = 5) {
  if (!text) return y;
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(60, 60, 60);
  const lines = doc.splitTextToSize(String(text), maxW);
  doc.text(lines, x, y);
  return y + lines.length * lineH;
}

// ─────────────────────────────────────────────────────────────────────
// MAIN: Generate Soil Analysis PDF Report
// ─────────────────────────────────────────────────────────────────────
export async function generateSoilReport({ params, result, farmerName, location }) {
  const jsPDF = await loadJsPDF();

  const now = new Date();
  const timestamp = now.toLocaleString("en-NG", {
    day: "2-digit", month: "short", year: "numeric",
    hour: "2-digit", minute: "2-digit", hour12: true
  });

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  let y = 0;
  let pageNum = 1;

  function newPage() {
    doc.addPage();
    pageNum++;
    drawWatermark(doc, pageW, pageH);
    drawFooter(doc, pageW, pageH, pageNum);
    y = drawHeader(doc, pageW, "Soil Analysis Report", timestamp);
  }

  function checkY(needed = 20) {
    if (y + needed > pageH - 20) newPage();
  }

  // ── Page 1 ──────────────────────────────────────────────────────────
  drawWatermark(doc, pageW, pageH);
  drawFooter(doc, pageW, pageH, pageNum);
  y = drawHeader(doc, pageW, "Soil Analysis Report", timestamp);

  // Farmer info box
  doc.setFillColor(248, 250, 251);
  doc.roundedRect(14, y, pageW - 28, 22, 3, 3, "F");
  doc.setDrawColor(30, 138, 76);
  doc.setLineWidth(0.3);
  doc.roundedRect(14, y, pageW - 28, 22, 3, 3, "D");

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 30, 30);
  doc.text("Farmer:", 20, y + 8);
  doc.setFont("helvetica", "normal");
  doc.text(farmerName ?? "TerraIQ+ User", 40, y + 8);

  doc.setFont("helvetica", "bold");
  doc.text("Location:", 20, y + 16);
  doc.setFont("helvetica", "normal");
  doc.text(location ?? "Nigeria", 42, y + 16);

  doc.setFont("helvetica", "bold");
  doc.text("Date:", pageW / 2 + 10, y + 8);
  doc.setFont("helvetica", "normal");
  doc.text(timestamp, pageW / 2 + 22, y + 8);

  // Soil rating badge
  const ratingColor = RATING_COLORS[result?.rating] ?? "#F59E0B";
  doc.setFillColor(...hexToRgb(ratingColor));
  doc.roundedRect(pageW - 58, y + 5, 38, 12, 3, 3, "F");
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text((result?.rating ?? "fair").toUpperCase(), pageW - 39, y + 13, { align: "center" });

  y += 30;

  // ── Soil Summary ────────────────────────────────────────────────────
  y = sectionHeading(doc, 14, y, "SOIL HEALTH SUMMARY", pageW);
  y = wrappedText(doc, result?.summary, 18, y, pageW - 36);
  y += 4;

  // ── Color Legend ────────────────────────────────────────────────────
  checkY(30);
  y = sectionHeading(doc, 14, y, "PARAMETER COLOR LEGEND", pageW);
  doc.setFontSize(7.5);
  doc.setFont("helvetica", "normal");

  const legendItems = Object.entries(PARAM_COLORS);
  const colW = (pageW - 28) / 3;
  legendItems.forEach(([key, { hex, name, unit }], i) => {
    const col = i % 3;
    const row = Math.floor(i / 3);
    const lx = 18 + col * colW;
    const ly = y + row * 8;
    doc.setFillColor(...hexToRgb(hex));
    doc.circle(lx, ly - 1, 2, "F");
    doc.setTextColor(40, 40, 40);
    doc.text(`${name}${unit ? ` (${unit})` : ""}`, lx + 5, ly);
  });
  y += Math.ceil(legendItems.length / 3) * 8 + 4;

  // ── Parameter Bars ──────────────────────────────────────────────────
  checkY(80);
  y = sectionHeading(doc, 14, y, "SOIL PARAMETER ANALYSIS", pageW);

  const cls = result?.classifications ?? {};
  const paramEntries = [
    ["nitrogen",       params?.nitrogen,       "mg/kg"],
    ["phosphorus",     params?.phosphorus,     "mg/kg"],
    ["potassium",      params?.potassium,      "mg/kg"],
    ["ph",             params?.ph,             ""],
    ["organic_carbon", params?.organic_carbon, "%"],
    ["moisture",       params?.moisture,       "%"],
  ].filter(([k, v]) => v !== undefined && v !== "" && v !== null && v !== 0);

  // Two columns
  const mid = Math.ceil(paramEntries.length / 2);
  const col1 = paramEntries.slice(0, mid);
  const col2 = paramEntries.slice(mid);
  const colBarW = 70;

  let maxY = y;
  col1.forEach(([key, val, unit]) => {
    const { hex, name } = PARAM_COLORS[key] ?? { hex: "#6B7280", name: key };
    maxY = drawParamBar(doc, 18, y + (col1.indexOf([key, val, unit]) || 0) * 13, name, val, unit, cls[key], hex, colBarW);
  });

  let y2 = y;
  col2.forEach(([key, val, unit]) => {
    const { hex, name } = PARAM_COLORS[key] ?? { hex: "#6B7280", name: key };
    y2 = drawParamBar(doc, pageW / 2 + 4, y2, name, val, unit, cls[key], hex, colBarW);
  });

  y = Math.max(maxY, y2) + 4;

  // Status level legend
  checkY(18);
  doc.setFontSize(7);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(120, 120, 120);
  const levelLegend = [
    ["#EF4444", "Critically Low / Too High"],
    ["#F97316", "Low / Acidic"],
    ["#EAB308", "Slightly High"],
    ["#22C55E", "Sufficient / Optimal"],
  ];
  let lx = 18;
  levelLegend.forEach(([color, label]) => {
    doc.setFillColor(...hexToRgb(color));
    doc.circle(lx, y - 1, 1.5, "F");
    doc.setTextColor(100, 100, 100);
    doc.text(label, lx + 4, y);
    lx += 50;
  });
  y += 8;

  // ── Best Crops ──────────────────────────────────────────────────────
  checkY(20);
  y = sectionHeading(doc, 14, y, "RECOMMENDED CROPS FOR THIS SOIL", pageW);
  const crops = result?.best_crops ?? [];
  if (crops.length) {
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);
    crops.forEach((crop, i) => {
      const cx = 18 + (i % 4) * 46;
      const cy = y + Math.floor(i / 4) * 8;
      doc.setFillColor(220, 245, 225);
      doc.roundedRect(cx - 2, cy - 4.5, 42, 7, 2, 2, "F");
      doc.setTextColor(30, 138, 76);
      doc.text(`✓ ${crop}`, cx + 1, cy);
    });
    y += Math.ceil(crops.length / 4) * 8 + 6;
  }

  // ── Fertilizer Recommendations ──────────────────────────────────────
  checkY(60);
  y = sectionHeading(doc, 14, y, "FERTILIZER RECOMMENDATIONS", pageW);
  const fert = result?.fertilizer_recommendation ?? {};

  // Synthetic
  if (fert.synthetic) {
    checkY(22);
    doc.setFillColor(255, 251, 235);
    doc.roundedRect(14, y, pageW - 28, 20, 2, 2, "F");
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text(`Synthetic: ${fert.synthetic.name ?? ""}`, 18, y + 7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(80, 80, 80);
    const synthLine = [fert.synthetic.rate, fert.synthetic.timing].filter(Boolean).join(" · ");
    y = wrappedText(doc, synthLine, 18, y + 13, pageW - 36);
    y += 4;
  }

  // Compost
  if (fert.compost) {
    checkY(22);
    doc.setFillColor(240, 253, 244);
    doc.roundedRect(14, y, pageW - 28, 20, 2, 2, "F");
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text(`Organic: ${fert.compost.name ?? ""}`, 18, y + 7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(80, 80, 80);
    y = wrappedText(doc, fert.compost.description ?? fert.compost.benefit, 18, y + 13, pageW - 36);
    y += 4;
  }

  // Biochar
  if (fert.biochar) {
    checkY(22);
    doc.setFillColor(254, 243, 199);
    doc.roundedRect(14, y, pageW - 28, 20, 2, 2, "F");
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text(`Biochar: ${fert.biochar.name ?? ""}`, 18, y + 7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(80, 80, 80);
    y = wrappedText(doc, fert.biochar.benefit_for_this_soil ?? fert.biochar.description, 18, y + 13, pageW - 36);
    y += 4;
  }

  // ── Improvement Steps ───────────────────────────────────────────────
  checkY(30);
  y = sectionHeading(doc, 14, y, "IMPROVEMENT ACTION PLAN", pageW);
  const steps = result?.improvement_steps ?? [];
  steps.forEach((step, i) => {
    checkY(12);
    doc.setFillColor(30, 138, 76);
    doc.circle(20, y - 1, 3.5, "F");
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text(String(i + 1), 20, y, { align: "center" });
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);
    y = wrappedText(doc, step, 28, y, pageW - 44);
    y += 3;
  });

  // ── Urgent Actions ──────────────────────────────────────────────────
  const urgent = result?.urgent_actions ?? [];
  if (urgent.length) {
    checkY(20);
    y = sectionHeading(doc, 14, y, "⚠ URGENT ACTIONS REQUIRED", pageW);
    doc.setFillColor(254, 226, 226);
    doc.roundedRect(14, y, pageW - 28, urgent.length * 10 + 6, 2, 2, "F");
    urgent.forEach((action, i) => {
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(185, 28, 28);
      y = wrappedText(doc, `• ${action}`, 18, y + 2, pageW - 36);
      y += 2;
    });
    y += 4;
  }

  // ── Season Advice ───────────────────────────────────────────────────
  if (result?.season_advice) {
    checkY(20);
    y = sectionHeading(doc, 14, y, "SEASON PLANTING ADVICE", pageW);
    y = wrappedText(doc, result.season_advice, 18, y, pageW - 36);
    y += 6;
  }

  // ── Weed Risk ───────────────────────────────────────────────────────
  if (result?.weed_risk) {
    checkY(20);
    doc.setFontSize(8.5);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    const weedColor = result.weed_risk === "high" ? "#EF4444" : result.weed_risk === "moderate" ? "#F59E0B" : "#22C55E";
    doc.text("Weed Risk:", 14, y);
    doc.setFillColor(...hexToRgb(weedColor));
    doc.roundedRect(38, y - 5, 20, 7, 2, 2, "F");
    doc.setFontSize(7.5);
    doc.setTextColor(255, 255, 255);
    doc.text(result.weed_risk.toUpperCase(), 48, y, { align: "center" });
    y += 6;
    y = wrappedText(doc, result.weed_risk_explanation, 18, y, pageW - 36);
    y += 4;
  }

  // Save
  const fname = `TerraIQ_Soil_Report_${now.toISOString().slice(0, 10)}.pdf`;
  doc.save(fname);
  return fname;
}

// ─────────────────────────────────────────────────────────────────────
// MAIN: Generate Plant Scan PDF Report
// ─────────────────────────────────────────────────────────────────────
export async function generateScanReport({ result, farmerName, location, imageDataUrl }) {
  const jsPDF = await loadJsPDF();

  const now = new Date();
  const timestamp = now.toLocaleString("en-NG", {
    day: "2-digit", month: "short", year: "numeric",
    hour: "2-digit", minute: "2-digit", hour12: true
  });

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  let y = 0;
  let pageNum = 1;

  drawWatermark(doc, pageW, pageH);
  drawFooter(doc, pageW, pageH, pageNum);
  y = drawHeader(doc, pageW, "Crop Scan Report", timestamp);

  // Farmer info box
  doc.setFillColor(248, 250, 251);
  doc.roundedRect(14, y, pageW - 28, 18, 3, 3, "F");
  doc.setFontSize(8.5);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 30, 30);
  doc.text("Farmer:", 18, y + 7);
  doc.setFont("helvetica", "normal");
  doc.text(farmerName ?? "TerraIQ+ User", 38, y + 7);
  doc.setFont("helvetica", "bold");
  doc.text("Location:", 18, y + 14);
  doc.setFont("helvetica", "normal");
  doc.text(location ?? "Nigeria", 40, y + 14);
  doc.setFont("helvetica", "bold");
  doc.text("Date:", pageW / 2, y + 7);
  doc.setFont("helvetica", "normal");
  doc.text(timestamp, pageW / 2 + 14, y + 7);
  y += 24;

  // Scan image (if provided)
  if (imageDataUrl) {
    try {
      const imgX = pageW - 14 - 50;
      doc.addImage(imageDataUrl, "JPEG", imgX, y, 50, 40, undefined, "MEDIUM");
      doc.setDrawColor(200, 200, 200);
      doc.roundedRect(imgX, y, 50, 40, 2, 2, "D");
    } catch (e) { /* image embed failed, skip */ }
  }

  // ── Identification ──────────────────────────────────────────────────
  y = sectionHeading(doc, 14, y, "PLANT IDENTIFICATION", pageW);

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 138, 76);
  doc.text(result?.crop_identified ?? "Unknown Plant", 18, y);
  y += 6;

  doc.setFontSize(9);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(100, 100, 100);
  doc.text(result?.scientific_name ?? "", 18, y);
  y += 6;

  // Confidence bar
  const conf = result?.identification_confidence ?? result?.confidence ?? 0;
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(60, 60, 60);
  doc.text(`Identification Confidence: ${conf}%`, 18, y);
  y += 4;
  doc.setFillColor(220, 220, 220);
  doc.roundedRect(18, y, 120, 4, 1.5, 1.5, "F");
  const confColor = conf >= 80 ? "#22C55E" : conf >= 60 ? "#F59E0B" : "#EF4444";
  doc.setFillColor(...hexToRgb(confColor));
  doc.roundedRect(18, y, 120 * conf / 100, 4, 1.5, 1.5, "F");
  y += 8;

  // Type badges
  if (result?.plant_type) {
    doc.setFillColor(220, 245, 225);
    doc.roundedRect(18, y - 4.5, 28, 7, 2, 2, "F");
    doc.setFontSize(7);
    doc.setTextColor(30, 138, 76);
    doc.text((result.plant_type ?? "").toUpperCase(), 32, y, { align: "center" });
  }
  if (result?.is_weed) {
    doc.setFillColor(254, 226, 226);
    doc.roundedRect(50, y - 4.5, 18, 7, 2, 2, "F");
    doc.setFontSize(7);
    doc.setTextColor(185, 28, 28);
    doc.text("WEED", 59, y, { align: "center" });
  }
  if (result?.is_healthy) {
    doc.setFillColor(220, 245, 225);
    doc.roundedRect(50, y - 4.5, 18, 7, 2, 2, "F");
    doc.setFontSize(7);
    doc.setTextColor(30, 138, 76);
    doc.text("HEALTHY", 59, y, { align: "center" });
  }
  y += 10;

  // Notes
  if (result?.identification_notes) {
    doc.setFontSize(7.5);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(120, 120, 120);
    y = wrappedText(doc, `Visual features: ${result.identification_notes}`, 18, y, pageW - 36);
    y += 4;
  }

  // ── Diagnosis ───────────────────────────────────────────────────────
  if (!result?.is_healthy && result?.diagnosis) {
    y = sectionHeading(doc, 14, y, "DIAGNOSIS", pageW);

    // Severity badge
    const sev = result?.severity ?? "low";
    const sevColor = SEVERITY_COLORS[sev] ?? "#22C55E";
    doc.setFillColor(...hexToRgb(sevColor));
    doc.roundedRect(18, y - 4.5, 30, 7, 2, 2, "F");
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text(`${sev.toUpperCase()} SEVERITY`, 33, y, { align: "center" });
    y += 8;

    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text(result.diagnosis, 18, y);
    y += 6;

    if (result?.severity_explanation) {
      y = wrappedText(doc, result.severity_explanation, 18, y, pageW - 36);
      y += 4;
    }

    // Immediate action
    if (result?.immediate_action) {
      doc.setFillColor(254, 243, 199);
      doc.roundedRect(14, y, pageW - 28, 14, 2, 2, "F");
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(120, 53, 15);
      doc.text("⚡ Immediate Action:", 18, y + 6);
      y = wrappedText(doc, result.immediate_action, 18, y + 11, pageW - 36);
      y += 4;
    }
  }

  // ── Treatment Steps ─────────────────────────────────────────────────
  if (result?.steps?.length) {
    y = sectionHeading(doc, 14, y, "TREATMENT STEPS", pageW);
    result.steps.forEach((step, i) => {
      doc.setFillColor(30, 138, 76);
      doc.circle(20, y - 1, 3.5, "F");
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(255, 255, 255);
      doc.text(String(i + 1), 20, y, { align: "center" });
      doc.setFont("helvetica", "normal");
      doc.setTextColor(40, 40, 40);
      y = wrappedText(doc, step, 28, y, pageW - 44);
      y += 3;
    });
    y += 2;
  }

  // ── Local Products ──────────────────────────────────────────────────
  if (result?.local_products?.length) {
    y = sectionHeading(doc, 14, y, "LOCAL PRODUCTS", pageW);
    const colW2 = (pageW - 28) / 2;
    result.local_products.forEach((p, i) => {
      const px = 14 + (i % 2) * colW2;
      const py = y + Math.floor(i / 2) * 14;
      doc.setFillColor(248, 250, 251);
      doc.roundedRect(px + 1, py - 1, colW2 - 4, 12, 2, 2, "F");
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 30, 30);
      doc.text(p.name ?? "", px + 4, py + 5);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(30, 138, 76);
      if (p.price_naira) doc.text(`₦${p.price_naira.toLocaleString()}`, px + 4, py + 10);
      if (p.where) doc.text(p.where, px + colW2 / 2, py + 10, { align: "center" });
    });
    y += Math.ceil((result.local_products.length) / 2) * 14 + 4;
  }

  // ── Organic Option ──────────────────────────────────────────────────
  if (result?.organic_option) {
    y = sectionHeading(doc, 14, y, "ORGANIC OPTION", pageW);
    doc.setFillColor(240, 253, 244);
    doc.roundedRect(14, y, pageW - 28, 16, 2, 2, "F");
    y = wrappedText(doc, result.organic_option, 18, y + 6, pageW - 36);
    y += 8;
  }

  // ── Prevention ──────────────────────────────────────────────────────
  if (result?.prevention) {
    y = sectionHeading(doc, 14, y, "PREVENTION", pageW);
    y = wrappedText(doc, result.prevention, 18, y, pageW - 36);
    y += 4;
  }

  // ── Weed Action ─────────────────────────────────────────────────────
  if (result?.is_weed && result?.weed_action) {
    y = sectionHeading(doc, 14, y, "WEED CONTROL", pageW);
    doc.setFillColor(254, 226, 226);
    doc.roundedRect(14, y, pageW - 28, 16, 2, 2, "F");
    y = wrappedText(doc, result.weed_action, 18, y + 6, pageW - 36);
    y += 8;
  }

  const fname = `TerraIQ_Scan_Report_${now.toISOString().slice(0, 10)}.pdf`;
  doc.save(fname);
  return fname;
}
