// ─── src/lib/generateReport.js ────────────────────────────────────────
// TerraIQ+ PDF Report Generator
// Draws real bar charts + pie chart using jsPDF primitives
// No $-sign math rendering issues — all text sanitized

import { jsPDF } from "jspdf";

// ── Brand palette ─────────────────────────────────────────────────────
const C = {
  green:   [30, 138, 76],
  greenL:  [52, 178, 98],
  white:   [255, 255, 255],
  ink:     [15, 31, 23],
  gray:    [100, 110, 105],
  grayL:   [210, 218, 214],
  bg:      [248, 250, 249],
  amber:   [217, 119, 6],
  red:     [220, 38, 38],
  orange:  [234, 88, 12],
};

// Parameter colors — each nutrient has its own color throughout the PDF
const PCOL = {
  nitrogen:       [59,  130, 246],
  phosphorus:     [245, 158, 11],
  potassium:      [249, 115, 22],
  ph:             [139, 92,  246],
  organic_carbon: [120, 53,  15],
  moisture:       [6,   182, 212],
};
const PNAME = {
  nitrogen: "Nitrogen", phosphorus: "Phosphorus", potassium: "Potassium",
  ph: "pH Level", organic_carbon: "Organic Carbon", moisture: "Moisture",
};
const PUNIT = {
  nitrogen: "mg/kg", phosphorus: "mg/kg", potassium: "mg/kg",
  ph: "", organic_carbon: "%", moisture: "%",
};

const S2P = { 1: 14, 2: 34, 3: 64, 4: 90 };

function levelRgb(level) {
  if (["critically_low","too_high","too_acidic","too_alkaline","waterlogged","critically_dry"].includes(level)) return C.red;
  if (["low","acidic","dry"].includes(level)) return C.orange;
  if (["slightly_alkaline","wet"].includes(level)) return C.amber;
  return C.green;
}

const RATING_RGB = { excellent:[22,163,74], good:[34,197,94], fair:[217,119,6], poor:[220,38,38] };
const SEV_RGB    = { none:[34,197,94], low:[34,197,94], moderate:[217,119,6], high:[234,88,12], critical:[220,38,38] };

// ── Text sanitizer ────────────────────────────────────────────────────
function safe(str) {
  if (str === null || str === undefined) return "";
  return String(str)
    .replace(/\$/g, "")
    .replace(/[^\x00-\xFF]/g, c => {
      const map = { "\u20A6":"NGN ", "\u2013":"-", "\u2014":"-", "\u2019":"'", "\u2018":"'", "\u201C":'"', "\u201D":'"' };
      return map[c] ?? "";
    })
    .replace(/NGN\s+/g, "NGN ")
    .trim();
}

function naira(amount) {
  if (!amount && amount !== 0) return "";
  return `NGN ${Number(amount).toLocaleString("en-NG")}`;
}

function ts() {
  return new Date().toLocaleString("en-NG", {
    day:"2-digit", month:"short", year:"numeric",
    hour:"2-digit", minute:"2-digit", hour12:true,
  });
}

function watermark(doc, W, H) {
  doc.saveGraphicsState();
  doc.setGState(new doc.GState({ opacity: 0.04 }));
  doc.setFontSize(90);
  doc.setFont("helvetica","bold");
  doc.setTextColor(...C.green);
  doc.text("TerraIQ+", W/2, H/2, { align:"center", angle:35 });
  doc.restoreGraphicsState();
}

function pageHeader(doc, W, title, stamp) {
  doc.setFillColor(...C.green);
  doc.rect(0, 0, W, 22, "F");
  doc.setFontSize(13); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
  doc.text("TerraIQ+", 14, 14);
  doc.setFontSize(9); doc.setFont("helvetica","normal");
  doc.text(safe(title), W/2, 14, { align:"center" });
  doc.setFontSize(7.5);
  doc.text(stamp, W-14, 14, { align:"right" });
  return 30;
}

function pageFooter(doc, W, H, num) {
  doc.setDrawColor(...C.green); doc.setLineWidth(0.3);
  doc.line(14, H-14, W-14, H-14);
  doc.setFontSize(7); doc.setFont("helvetica","normal"); doc.setTextColor(...C.gray);
  doc.text("Generated by TerraIQ+ · Precision Agriculture for Nigerian Farmers", 14, H-8);
  doc.text(`Page ${num}`, W-14, H-8, { align:"right" });
}

function secHead(doc, x, y, text, W) {
  doc.setFillColor(241,247,244);
  doc.rect(x, y-5, W-x*2, 9, "F");
  doc.setDrawColor(...C.green); doc.setLineWidth(0.6);
  doc.line(x, y-5, x, y+4);
  doc.setFontSize(9); doc.setFont("helvetica","bold"); doc.setTextColor(...C.green);
  doc.text(safe(text), x+4, y);
  return y + 11;
}

function wrap(doc, text, x, y, maxW, lh=5.2) {
  if (!text) return y;
  doc.setFontSize(8); doc.setFont("helvetica","normal"); doc.setTextColor(...C.ink);
  const lines = doc.splitTextToSize(safe(text), maxW);
  doc.text(lines, x, y);
  return y + lines.length * lh;
}

// ── CHART: Horizontal bar chart for soil parameters ───────────────────
function drawBarChart(doc, x, y, params, classifications, W) {
  const chartW   = W - x*2;
  const barH     = 8;
  const gap      = 4;
  const labelW   = 52;
  const valueW   = 26;
  const barAreaW = chartW - labelW - valueW - 6;

  const entries = Object.entries(PCOL).filter(([k]) => {
    const v = params[k];
    return v !== undefined && v !== null && v !== "" && +v !== 0;
  });

  if (!entries.length) return y;

  y = secHead(doc, x, y, "SOIL PARAMETER BAR CHART", W);

  entries.forEach(([key, rgb]) => {
    const cls   = classifications?.[key];
    const val   = params[key];
    const pct   = cls ? (S2P[cls.score] ?? 50) : 50;
    const bRgb  = cls ? levelRgb(cls.level) : C.green;
    const unit  = PUNIT[key] ?? "";
    const lv    = cls?.label ?? "";

    doc.setFontSize(7.5); doc.setFont("helvetica","bold"); doc.setTextColor(...C.ink);
    doc.text(safe(PNAME[key] ?? key), x, y + barH*0.65);

    doc.setFillColor(...rgb);
    doc.circle(x + labelW - 6, y + barH*0.5, 2, "F");

    const bx = x + labelW;
    doc.setFillColor(...C.grayL);
    doc.roundedRect(bx, y+1, barAreaW, barH-2, 1.5, 1.5, "F");

    const fillW = Math.max(4, barAreaW * pct / 100);
    doc.setFillColor(...bRgb);
    doc.roundedRect(bx, y+1, fillW, barH-2, 1.5, 1.5, "F");

    doc.setFontSize(6.5); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
    if (fillW > 20) doc.text(`${val}${unit}`, bx + fillW/2, y + barH*0.62, { align:"center" });

    const bvx = bx + barAreaW + 3;
    doc.setFillColor(...bRgb);
    doc.roundedRect(bvx, y+1, valueW, barH-2, 1.5, 1.5, "F");
    doc.setFontSize(5.5); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
    doc.text(safe(lv).toUpperCase(), bvx + valueW/2, y + barH*0.65, { align:"center" });

    if (fillW <= 20) {
      doc.setFontSize(6.5); doc.setFont("helvetica","normal"); doc.setTextColor(...C.ink);
      doc.text(`${val}${unit}`, bx+2, y + barH*0.65);
    }

    y += barH + gap;
  });

  return y + 4;
}

// ── CHART: Pie chart for soil health composition ──────────────────────
function drawPieChart(doc, cx, cy, r, classifications) {
  const entries = Object.entries(PCOL).filter(([k]) => classifications?.[k]);
  if (!entries.length) return;

  const scores = entries.map(([k]) => classifications[k]?.score ?? 2);
  const total  = scores.reduce((a,b) => a+b, 0) || 1;
  let angle    = -Math.PI / 2;

  entries.forEach(([key, rgb], i) => {
    const slice = (scores[i] / total) * Math.PI * 2;
    const end   = angle + slice;
    const mid   = angle + slice / 2;
    const steps = Math.max(8, Math.round(slice * 20));

    doc.setFillColor(...rgb);
    doc.setDrawColor(...C.white);
    doc.setLineWidth(0.5);

    const pts = [[cx, cy]];
    for (let s = 0; s <= steps; s++) {
      const a = angle + (slice * s / steps);
      pts.push([cx + r * Math.cos(a), cy + r * Math.sin(a)]);
    }

    doc.lines(
      pts.slice(1).map((p, idx) => {
        const prev = pts[idx];
        return [p[0]-prev[0], p[1]-prev[1]];
      }),
      pts[0][0], pts[0][1], [1,1], "FD"
    );

    if (slice > 0.35) {
      const lx = cx + (r * 0.62) * Math.cos(mid);
      const ly = cy + (r * 0.62) * Math.sin(mid);
      doc.setFontSize(5.5); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
      doc.text(`${Math.round(scores[i]/total*100)}%`, lx, ly, { align:"center" });
    }

    angle = end;
  });

  // Donut hole
  doc.setFillColor(...C.white);
  doc.circle(cx, cy, r * 0.38, "F");

  doc.setFontSize(6); doc.setFont("helvetica","bold"); doc.setTextColor(...C.green);
  doc.text("SOIL", cx, cy-1, { align:"center" });
  doc.text("HEALTH", cx, cy+4, { align:"center" });
}

// ── CHART: Legend for pie chart ───────────────────────────────────────
function drawPieLegend(doc, x, y, classifications) {
  const entries = Object.entries(PCOL).filter(([k]) => classifications?.[k]);
  entries.forEach(([key, rgb], i) => {
    const cls = classifications[key];
    const ly  = y + i * 10;
    doc.setFillColor(...rgb);
    doc.roundedRect(x, ly-3, 5, 5, 1, 1, "F");
    doc.setFontSize(7); doc.setFont("helvetica","bold"); doc.setTextColor(...C.ink);
    doc.text(safe(PNAME[key]), x+7, ly+1);
    doc.setFont("helvetica","normal"); doc.setTextColor(...C.gray);
    doc.text(safe(cls?.label ?? ""), x+7, ly+5.5);
  });
  return y + entries.length * 10 + 4;
}

// ── CHART: Mini confidence gauge ──────────────────────────────────────
function drawConfidenceGauge(doc, x, y, confidence, W) {
  const trackW = W - x*2;
  const conf   = Math.min(100, Math.max(0, +confidence || 0));
  const rgb    = conf >= 80 ? C.green : conf >= 60 ? C.amber : C.red;

  doc.setFontSize(8); doc.setFont("helvetica","bold"); doc.setTextColor(...C.ink);
  doc.text(`Identification Confidence: ${conf}%`, x, y);
  y += 4;

  doc.setFillColor(...C.grayL);
  doc.roundedRect(x, y, trackW, 5, 2, 2, "F");
  doc.setFillColor(...rgb);
  doc.roundedRect(x, y, trackW * conf/100, 5, 2, 2, "F");

  [60, 80].forEach(pct => {
    const tx = x + trackW * pct/100;
    doc.setDrawColor(...C.white); doc.setLineWidth(0.5);
    doc.line(tx, y, tx, y+5);
    doc.setFontSize(5.5); doc.setTextColor(...C.gray);
    doc.text(`${pct}%`, tx, y+9, { align:"center" });
  });

  return y + 14;
}

// ─────────────────────────────────────────────────────────────────────
// SOIL ANALYSIS REPORT
// ─────────────────────────────────────────────────────────────────────
export async function generateSoilReport({ params, result, farmerName, location }) {
  const doc = new jsPDF({ orientation:"portrait", unit:"mm", format:"a4" });
  const W   = doc.internal.pageSize.getWidth();
  const H   = doc.internal.pageSize.getHeight();
  const stamp = ts();
  let y = 0, pageNum = 1;

  const checkY = (need=20) => {
    if (y + need > H - 20) {
      doc.addPage(); pageNum++;
      watermark(doc, W, H);
      pageFooter(doc, W, H, pageNum);
      y = pageHeader(doc, W, "Soil Analysis Report", stamp);
    }
  };

  watermark(doc, W, H);
  pageFooter(doc, W, H, pageNum);
  y = pageHeader(doc, W, "Soil Analysis Report", stamp);

  // ── Info box ─────────────────────────────────────────────────────
  doc.setFillColor(...C.bg);
  doc.roundedRect(14, y, W-28, 22, 3, 3, "F");
  doc.setDrawColor(...C.green); doc.setLineWidth(0.3);
  doc.roundedRect(14, y, W-28, 22, 3, 3, "D");
  doc.setFontSize(8.5); doc.setFont("helvetica","bold"); doc.setTextColor(...C.ink);
  doc.text("Farmer:", 19, y+8);
  doc.setFont("helvetica","normal");
  doc.text(safe(farmerName ?? "TerraIQ+ User"), 40, y+8);
  doc.setFont("helvetica","bold");
  doc.text("Location:", 19, y+15);
  doc.setFont("helvetica","normal");
  doc.text(safe(location ?? "Nigeria"), 42, y+15);
  doc.setFont("helvetica","bold");
  doc.text("Date:", W/2+5, y+8);
  doc.setFont("helvetica","normal");
  doc.text(stamp, W/2+18, y+8);
  const rRgb = RATING_RGB[result?.rating] ?? RATING_RGB.fair;
  doc.setFillColor(...rRgb);
  doc.roundedRect(W-52, y+6, 32, 10, 2.5, 2.5, "F");
  doc.setFontSize(9); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
  doc.text(safe(result?.rating ?? "fair").toUpperCase(), W-36, y+13, { align:"center" });
  y += 30;

  // ── Summary ──────────────────────────────────────────────────────
  y = secHead(doc, 14, y, "SOIL HEALTH SUMMARY", W);
  y = wrap(doc, result?.summary, 18, y, W-36);
  y += 5;

  // ── Color legend ──────────────────────────────────────────────────
  checkY(22);
  y = secHead(doc, 14, y, "PARAMETER COLOR LEGEND", W);
  const paramKeys = Object.keys(PCOL).filter(k => params?.[k] !== undefined && params?.[k] !== "" && +params?.[k] !== 0);
  const legendRows = Math.ceil(paramKeys.length / 2);
  paramKeys.forEach((key, i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const lx  = 18 + col * ((W-36)/2);
    const ly  = y + row * 8;
    doc.setFillColor(...PCOL[key]);
    doc.circle(lx, ly-1, 2.2, "F");
    doc.setFontSize(7.5); doc.setFont("helvetica","normal"); doc.setTextColor(...C.ink);
    doc.text(`${PNAME[key]}${PUNIT[key] ? " (" + PUNIT[key] + ")" : ""}`, lx+5, ly);
  });
  y += legendRows * 8 + 4;

  const lvLegend = [
    [C.red,    "Critical / Too High"],
    [C.orange, "Low"],
    [C.amber,  "Slightly Elevated"],
    [C.green,  "Sufficient / Optimal"],
  ];
  let lx2 = 18;
  doc.setFontSize(7); doc.setFont("helvetica","italic");
  lvLegend.forEach(([rgb, label]) => {
    doc.setFillColor(...rgb); doc.circle(lx2, y-1, 1.6, "F");
    doc.setTextColor(...C.gray); doc.text(safe(label), lx2+4, y);
    lx2 += 46;
  });
  y += 8;

  // ── Bar chart ─────────────────────────────────────────────────────
  checkY(80);
  y = drawBarChart(doc, 14, y, params ?? {}, result?.classifications ?? {}, W);

  // ── Pie chart + legend ────────────────────────────────────────────
  const cls = result?.classifications ?? {};
  if (Object.keys(cls).length > 0) {
    const pieR = 26;
    checkY(pieR * 2 + 24);
    y = secHead(doc, 14, y, "SOIL HEALTH COMPOSITION (SCORE-WEIGHTED)", W);

    const pieCX = 14 + pieR + 8;
    const pieCY = y + pieR + 2;
    drawPieChart(doc, pieCX, pieCY, pieR, cls);

    // Legend sits right of the pie — only if it fits
    const legendX = pieCX + pieR + 14;
    if (legendX + 60 < W) {
      drawPieLegend(doc, legendX, y + 2, cls);
    } else {
      // Fallback: legend below pie
      const belowY = pieCY + pieR + 8;
      drawPieLegend(doc, 18, belowY, cls);
    }

    y = pieCY + pieR + 10;
  }

  // ── Measured values table ─────────────────────────────────────────
  checkY(40);
  y = secHead(doc, 14, y, "ACTUAL MEASURED VALUES", W);

  const colHeaders = ["Parameter", "Value", "Unit", "Status", "Optimal Range"];
  const cW = [(W-28)*0.28, (W-28)*0.14, (W-28)*0.12, (W-28)*0.22, (W-28)*0.24];
  let tx = 14;

  doc.setFillColor(...C.green);
  doc.rect(14, y-4, W-28, 8, "F");
  doc.setFontSize(7); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
  colHeaders.forEach((col, i) => { doc.text(safe(col), tx+2, y); tx += cW[i]; });
  y += 5;

  const OPTIMAL = {
    nitrogen:       "20-40 mg/kg",
    phosphorus:     "12-30 mg/kg",
    potassium:      "80-180 mg/kg",
    ph:             "5.5-6.8",
    organic_carbon: "1.0-2.5%",
    moisture:       "30-60%",
  };

  Object.entries(PCOL).forEach(([key, rgb], i) => {
    const val = params?.[key];
    if (val === undefined || val === null || val === "" || +val === 0) return;
    const c2   = cls[key];
    const bRgb = c2 ? levelRgb(c2.level) : C.green;
    checkY(10);
    if (i % 2 === 0) { doc.setFillColor(245,250,247); doc.rect(14, y-3.5, W-28, 8, "F"); }

    tx = 14;
    doc.setFontSize(7); doc.setFont("helvetica","bold"); doc.setTextColor(...rgb);
    doc.text(safe(PNAME[key]), tx+2, y); tx += cW[0];
    doc.setTextColor(...C.ink);
    doc.text(String(val), tx+2, y); tx += cW[1];
    doc.setFont("helvetica","normal"); doc.setTextColor(...C.gray);
    doc.text(safe(PUNIT[key]), tx+2, y); tx += cW[2];
    doc.setFillColor(...bRgb);
    doc.roundedRect(tx+1, y-3, cW[3]-4, 6, 1, 1, "F");
    doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
    doc.text(safe(c2?.label ?? "").toUpperCase(), tx + (cW[3]-4)/2 + 1, y, { align:"center" });
    tx += cW[3];
    doc.setFont("helvetica","normal"); doc.setTextColor(...C.gray);
    doc.text(safe(OPTIMAL[key] ?? "-"), tx+2, y);
    y += 8;
  });
  y += 4;

  // ── Recommended crops ─────────────────────────────────────────────
  const crops = (result?.best_crops ?? []).map(c => safe(c)).filter(Boolean);
  if (crops.length) {
    checkY(22);
    y = secHead(doc, 14, y, "RECOMMENDED CROPS FOR THIS SOIL", W);
    const perRow = 4;
    crops.forEach((crop, i) => {
      const cx2 = 18 + (i % perRow) * ((W-36)/perRow);
      const cy2 = y + Math.floor(i / perRow) * 9;
      doc.setFillColor(220, 245, 225);
      doc.roundedRect(cx2-2, cy2-4.5, (W-36)/perRow - 2, 7, 2, 2, "F");
      doc.setFontSize(7.5); doc.setFont("helvetica","normal"); doc.setTextColor(...C.green);
      doc.text(safe(crop), cx2, cy2, { maxWidth: (W-36)/perRow - 4 });
    });
    y += Math.ceil(crops.length / perRow) * 9 + 6;
  }

  // ── Fertilizer recommendations ────────────────────────────────────
  // FIX: handles both "supplement" and "supplements" key variants from AI
  const fert = result?.fertilizer_recommendation ?? {};
  const fertItems = [
    { key:"synthetic",   label:"Synthetic Fertilizer",      bg:[255,251,235] },
    { key:"compost",     label:"Allamanda Compost",         bg:[240,253,244] },
    { key:"biochar",     label:"Allamanda Biochar",         bg:[254,243,199] },
    { key:"supplement",  label:"Allamanda Soil Supplement", bg:[254,232,232] },
    { key:"supplements", label:"Allamanda Soil Supplement", bg:[254,232,232] },
  ];
  const seen = new Set();
  const fertToRender = fertItems.filter(({ key }) => {
    if (!fert[key]) return false;
    const dk = key.replace(/s$/, "");
    if (seen.has(dk)) return false;
    seen.add(dk);
    return true;
  });

  if (fertToRender.length) {
    checkY(30);
    y = secHead(doc, 14, y, "FERTILIZER RECOMMENDATIONS", W);
    fertToRender.forEach(({ key, label, bg }) => {
      const item = fert[key]; if (!item) return;
      checkY(28);
      const desc = [
        item.description, item.benefit, item.benefit_for_this_soil,
        item.rate && `Rate: ${item.rate}`,
        item.timing && `Timing: ${item.timing}`,
      ].filter(Boolean).map(safe).join(" · ");
      const descLines = doc.splitTextToSize(safe(desc), W-40);
      const boxH = descLines.length * 5.2 + 16;
      doc.setFillColor(...bg);
      doc.roundedRect(14, y, W-28, boxH, 2, 2, "F");
      doc.setFontSize(8); doc.setFont("helvetica","bold"); doc.setTextColor(...C.ink);
      doc.text(safe(item.name ?? label), 18, y+7);
      doc.setFont("helvetica","normal"); doc.setTextColor(...C.gray);
      y = wrap(doc, desc, 18, y+13, W-36);
      y += 6;
    });
  }

  // ── Improvement action plan ───────────────────────────────────────
  const steps = result?.improvement_steps ?? [];
  if (steps.length) {
    checkY(30);
    y = secHead(doc, 14, y, "IMPROVEMENT ACTION PLAN", W);
    steps.forEach((step, i) => {
      checkY(14);
      doc.setFillColor(...C.green); doc.circle(20, y-1, 3.5, "F");
      doc.setFontSize(8); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
      doc.text(String(i+1), 20, y, { align:"center" });
      doc.setFont("helvetica","normal"); doc.setTextColor(...C.ink);
      y = wrap(doc, step, 28, y, W-44); y += 3;
    });
  }

  // ── Urgent actions ────────────────────────────────────────────────
  const urgent = result?.urgent_actions ?? [];
  if (urgent.length) {
    checkY(20);
    y = secHead(doc, 14, y, "URGENT ACTIONS REQUIRED", W);
    doc.setFillColor(254,226,226);
    doc.roundedRect(14, y, W-28, urgent.length*10+6, 2, 2, "F");
    urgent.forEach(action => {
      checkY(12);
      doc.setFontSize(8); doc.setFont("helvetica","normal"); doc.setTextColor(185,28,28);
      y = wrap(doc, `• ${safe(action)}`, 18, y+4, W-36); y += 2;
    });
    y += 4;
  }

  // ── Season planting advice ─────────────────────────────────────────
  if (result?.season_advice) {
    checkY(24);
    y = secHead(doc, 14, y, "SEASON PLANTING ADVICE", W);
    doc.setFillColor(240, 249, 244);
    const saLines = doc.splitTextToSize(safe(result.season_advice), W-40);
    const saH = saLines.length * 5.2 + 12;
    doc.roundedRect(14, y, W-28, saH, 2, 2, "F");
    y = wrap(doc, result.season_advice, 18, y+7, W-36); y += 8;
  }

  // ── Weed risk ─────────────────────────────────────────────────────
  if (result?.weed_risk) {
    checkY(18);
    y = secHead(doc, 14, y, "WEED RISK ASSESSMENT", W);
    const wRgb = result.weed_risk==="high" ? C.red : result.weed_risk==="moderate" ? C.amber : C.green;
    doc.setFontSize(8.5); doc.setFont("helvetica","bold"); doc.setTextColor(...C.ink);
    doc.text("Weed Risk:", 14, y);
    doc.setFillColor(...wRgb); doc.roundedRect(40, y-5, 22, 7, 2, 2, "F");
    doc.setFontSize(7); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
    doc.text(safe(result.weed_risk).toUpperCase(), 51, y, { align:"center" });
    y += 8;
    if (result.weed_risk_explanation) {
      y = wrap(doc, result.weed_risk_explanation, 18, y, W-36); y += 4;
    }
  }

  doc.save(`TerraIQ_Soil_Report_${new Date().toISOString().slice(0,10)}.pdf`);
}

// ─────────────────────────────────────────────────────────────────────
// SCAN REPORT
// ─────────────────────────────────────────────────────────────────────
export async function generateScanReport({ result, farmerName, location, imageDataUrl }) {
  const doc = new jsPDF({ orientation:"portrait", unit:"mm", format:"a4" });
  const W   = doc.internal.pageSize.getWidth();
  const H   = doc.internal.pageSize.getHeight();
  const stamp = ts();
  let y = 0, pageNum = 1;

  const checkY = (need=20) => {
    if (y + need > H - 20) {
      doc.addPage(); pageNum++;
      watermark(doc, W, H);
      pageFooter(doc, W, H, pageNum);
      y = pageHeader(doc, W, "Crop Scan Report", stamp);
    }
  };

  watermark(doc, W, H);
  pageFooter(doc, W, H, pageNum);
  y = pageHeader(doc, W, "Crop Scan Report", stamp);

  // ── Info box ─────────────────────────────────────────────────────
  doc.setFillColor(...C.bg);
  doc.roundedRect(14, y, W-28, 22, 3, 3, "F");
  doc.setDrawColor(...C.green); doc.setLineWidth(0.3);
  doc.roundedRect(14, y, W-28, 22, 3, 3, "D");
  doc.setFontSize(8.5); doc.setFont("helvetica","bold"); doc.setTextColor(...C.ink);
  doc.text("Farmer:", 18, y+8);
  doc.setFont("helvetica","normal"); doc.text(safe(farmerName ?? "TerraIQ+ User"), 40, y+8);
  doc.setFont("helvetica","bold"); doc.text("Location:", 18, y+15);
  doc.setFont("helvetica","normal"); doc.text(safe(location ?? "Nigeria"), 42, y+15);
  doc.setFont("helvetica","bold"); doc.text("Date:", W/2, y+8);
  doc.setFont("helvetica","normal"); doc.text(stamp, W/2+14, y+8);
  y += 28;

  // ── Scanned image ─────────────────────────────────────────────────
  const imgSrc = imageDataUrl || result?.imageDataUrl;
  if (imgSrc) {
    try {
      const imgY = y;
      const imgH = 52;
      doc.addImage(imgSrc, "JPEG", 14, imgY, W-28, imgH, undefined, "MEDIUM");
      doc.setDrawColor(...C.green); doc.setLineWidth(0.3);
      doc.roundedRect(14, imgY, W-28, imgH, 2, 2, "D");
      doc.setFontSize(7); doc.setFont("helvetica","italic"); doc.setTextColor(...C.gray);
      doc.text("Scanned plant image", 18, imgY + imgH - 3);
      y += imgH + 6;
    } catch(_) { /* image load failed — skip gracefully */ }
  }

  // ── Plant identification ──────────────────────────────────────────
  y = secHead(doc, 14, y, "PLANT IDENTIFICATION", W);
  doc.setFontSize(15); doc.setFont("helvetica","bold"); doc.setTextColor(...C.green);
  doc.text(safe(result?.crop_identified ?? "Unknown Plant"), 18, y);
  y += 6;
  if (result?.scientific_name) {
    doc.setFontSize(9); doc.setFont("helvetica","italic"); doc.setTextColor(...C.gray);
    doc.text(safe(result.scientific_name), 18, y);
    y += 6;
  }

  // ── Confidence gauge ──────────────────────────────────────────────
  const conf = Math.min(100, Math.max(0, +(result?.identification_confidence ?? result?.confidence ?? 0)));
  y = drawConfidenceGauge(doc, 18, y, conf, W);

  // ── Status badges ─────────────────────────────────────────────────
  let bx = 18;
  // plant_type is optional — only render if present
  if (result?.plant_type) {
    doc.setFillColor(...C.green);
    doc.roundedRect(bx, y-4.5, 30, 7, 2, 2, "F");
    doc.setFontSize(7); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
    doc.text(safe(result.plant_type).toUpperCase(), bx+15, y, { align:"center" }); bx += 34;
  }
  if (result?.is_weed) {
    doc.setFillColor(...C.orange);
    doc.roundedRect(bx, y-4.5, 18, 7, 2, 2, "F");
    doc.setFontSize(7); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
    doc.text("WEED", bx+9, y, { align:"center" }); bx += 22;
  }
  if (result?.is_healthy) {
    doc.setFillColor(...C.green);
    doc.roundedRect(bx, y-4.5, 22, 7, 2, 2, "F");
    doc.setFontSize(7); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
    doc.text("HEALTHY", bx+11, y, { align:"center" });
  }
  y += 12;

  // ── Health summary (was missing — now rendered) ───────────────────
  if (result?.health_summary) {
    checkY(18);
    const hsLines = doc.splitTextToSize(safe(result.health_summary), W-40);
    const hsH = hsLines.length * 5.2 + 12;
    doc.setFillColor(240, 249, 244);
    doc.roundedRect(14, y, W-28, hsH, 2, 2, "F");
    y = wrap(doc, result.health_summary, 18, y+7, W-36); y += 6;
  }

  if (result?.identification_notes) {
    checkY(12);
    doc.setFontSize(7.5); doc.setFont("helvetica","italic"); doc.setTextColor(...C.gray);
    y = wrap(doc, `Visual features: ${result.identification_notes}`, 18, y, W-36); y += 4;
  }

  // ── Diagnosis ─────────────────────────────────────────────────────
  if (!result?.is_healthy && result?.diagnosis) {
    checkY(50);
    y = secHead(doc, 14, y, "DIAGNOSIS", W);
    doc.setFontSize(10); doc.setFont("helvetica","bold"); doc.setTextColor(...C.ink);
    doc.text(safe(result.diagnosis), 18, y); y += 7;

    if (result?.severity_explanation) {
      y = wrap(doc, result.severity_explanation, 18, y, W-36); y += 4;
    }

    // Severity indicator
    checkY(18);
    y = secHead(doc, 14, y, "SEVERITY INDICATOR", W);
    const sev       = result?.severity ?? "low";
    const sevLevels = ["low","moderate","high","critical"];
    const sevIdx    = sevLevels.indexOf(sev);
    const sevW      = (W-36) / 4;
    sevLevels.forEach((lv, i) => {
      const sx       = 18 + i * sevW;
      const isActive = i <= sevIdx;
      const lvRgb    = SEV_RGB[lv] ?? C.green;
      doc.setFillColor(...(isActive ? lvRgb : C.grayL));
      doc.roundedRect(sx, y, sevW-2, 7, 1.5, 1.5, "F");
      doc.setFontSize(6.5); doc.setFont("helvetica","bold");
      doc.setTextColor(isActive ? 255 : 150, isActive ? 255 : 150, isActive ? 255 : 150);
      doc.text(lv.toUpperCase(), sx + (sevW-2)/2, y+4.5, { align:"center" });
    });
    y += 11;

    // Immediate action box
    if (result?.immediate_action) {
      checkY(20);
      const iaLines = doc.splitTextToSize(safe(result.immediate_action), W-40);
      const iaH = iaLines.length * 5.2 + 18;
      doc.setFillColor(254,243,199);
      doc.roundedRect(14, y, W-28, iaH, 2, 2, "F");
      doc.setFontSize(8); doc.setFont("helvetica","bold"); doc.setTextColor(120,53,15);
      doc.text("Immediate Action:", 18, y+7);
      y = wrap(doc, result.immediate_action, 18, y+13, W-36); y += 8;
    }
  }

  // ── Treatment steps ───────────────────────────────────────────────
  const steps = result?.steps ?? [];
  if (steps.length) {
    checkY(20);
    y = secHead(doc, 14, y, "TREATMENT STEPS", W);
    steps.forEach((step, i) => {
      checkY(14);
      doc.setFillColor(...C.green); doc.circle(20, y-1, 3.5, "F");
      doc.setFontSize(8); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
      doc.text(String(i+1), 20, y, { align:"center" });
      doc.setFont("helvetica","normal"); doc.setTextColor(...C.ink);
      y = wrap(doc, step, 28, y, W-44); y += 3;
    });
    y += 2;
  }

  // ── Local products ────────────────────────────────────────────────
  const products = result?.local_products ?? [];
  if (products.length) {
    checkY(20);
    y = secHead(doc, 14, y, "LOCAL PRODUCTS", W);
    const colW2 = (W-28)/2;
    products.forEach((p, i) => {
      if (i % 2 === 0) checkY(18);
      const px2 = 14 + (i%2)*colW2;
      const py2 = y + Math.floor(i/2)*16;
      doc.setFillColor(...C.bg);
      doc.roundedRect(px2+1, py2-1, colW2-4, 14, 2, 2, "F");
      doc.setFontSize(8); doc.setFont("helvetica","bold"); doc.setTextColor(...C.ink);
      doc.text(safe(p.name ?? ""), px2+4, py2+5);
      doc.setFont("helvetica","normal");
      if (p.price_naira) { doc.setTextColor(...C.green); doc.text(naira(p.price_naira), px2+4, py2+11); }
      if (p.where) { doc.setTextColor(...C.gray); doc.text(safe(p.where), px2+colW2/2, py2+11, { align:"center", maxWidth: colW2-8 }); }
    });
    y += Math.ceil(products.length/2)*16 + 4;
  }

  // ── Organic option ────────────────────────────────────────────────
  if (result?.organic_option) {
    checkY(20);
    y = secHead(doc, 14, y, "ORGANIC OPTION", W);
    doc.setFillColor(240,253,244);
    const orgLines = doc.splitTextToSize(safe(result.organic_option), W-40);
    const orgH = orgLines.length * 5.2 + 12;
    doc.roundedRect(14, y, W-28, orgH, 2, 2, "F");
    y = wrap(doc, result.organic_option, 18, y+7, W-36); y += 6;
  }

  // ── Prevention ────────────────────────────────────────────────────
  if (result?.prevention) {
    checkY(18);
    y = secHead(doc, 14, y, "PREVENTION", W);
    y = wrap(doc, result.prevention, 18, y, W-36); y += 6;
  }

  // ── Weed control ──────────────────────────────────────────────────
  if (result?.is_weed && result?.weed_action) {
    checkY(20);
    y = secHead(doc, 14, y, "WEED CONTROL", W);
    doc.setFillColor(254,226,226);
    const waLines = doc.splitTextToSize(safe(result.weed_action), W-40);
    const waH = waLines.length * 5.2 + 12;
    doc.roundedRect(14, y, W-28, waH, 2, 2, "F");
    doc.setTextColor(185,28,28);
    y = wrap(doc, result.weed_action, 18, y+7, W-36); y += 8;
  }

  // ── Healthy plant summary ──────────────────────────────────────────
  if (result?.is_healthy && !result?.diagnosis) {
    checkY(20);
    y = secHead(doc, 14, y, "PLANT HEALTH ASSESSMENT", W);
    doc.setFillColor(240, 253, 244);
    doc.roundedRect(14, y, W-28, 18, 2, 2, "F");
    doc.setFontSize(9); doc.setFont("helvetica","bold"); doc.setTextColor(...C.green);
    doc.text("No disease or pest detected", 18, y+7);
    doc.setFont("helvetica","normal"); doc.setFontSize(8); doc.setTextColor(...C.gray);
    doc.text("Continue current crop management practices.", 18, y+13);
    y += 22;
  }

  doc.save(`TerraIQ_Scan_Report_${new Date().toISOString().slice(0,10)}.pdf`);
}
