// ─── src/lib/generateReport.js ────────────────────────────────────────
// TerraIQ+ PDF Report Generator
// Draws real bar charts + pie chart using jsPDF primitives
// No $-sign math rendering issues — all text sanitized
// npm install jspdf  (one time)

import { jsPDF } from "jspdf";

// ── Brand palette ─────────────────────────────────────────────────────
const C = {
  green:   [30, 138, 76],
  greenL:  [52, 178, 98],
  white:   [255, 255, 255],
  ink:     [15, 31, 23],
  gray:    [100, 110, 105],
  grayL:   [210, 218, 214],
  bg:      [248, 250, 249],
  amber:   [217, 119, 6],
  red:     [220, 38, 38],
  orange:  [234, 88, 12],
};

// Parameter colors — each nutrient has its own color throughout the PDF
const PCOL = {
  nitrogen:       [59,  130, 246],   // blue
  phosphorus:     [245, 158, 11],    // amber
  potassium:      [249, 115, 22],    // orange
  ph:             [139, 92,  246],   // purple
  organic_carbon: [120, 53,  15],    // brown
  moisture:       [6,   182, 212],   // cyan
};
const PNAME = {
  nitrogen: "Nitrogen", phosphorus: "Phosphorus", potassium: "Potassium",
  ph: "pH Level", organic_carbon: "Organic Carbon", moisture: "Moisture",
};
const PUNIT = {
  nitrogen: "mg/kg", phosphorus: "mg/kg", potassium: "mg/kg",
  ph: "", organic_carbon: "%", moisture: "%",
};

// Score → percentage fill for bar
const S2P = { 1: 14, 2: 34, 3: 64, 4: 90 };

function levelRgb(level) {
  if (["critically_low","too_high","too_acidic","too_alkaline","waterlogged","critically_dry"].includes(level)) return C.red;
  if (["low","acidic","dry"].includes(level)) return C.orange;
  if (["slightly_alkaline","wet"].includes(level)) return C.amber;
  return C.green;
}

const RATING_RGB = { excellent:[22,163,74], good:[34,197,94], fair:[217,119,6], poor:[220,38,38] };
const SEV_RGB    = { low:[34,197,94], moderate:[217,119,6], high:[234,88,12], critical:[220,38,38] };

// ── Text sanitizer — remove $ signs that jsPDF renders as math ────────
function safe(str) {
  if (str === null || str === undefined) return "";
  return String(str)
    .replace(/\$/g, "")          // remove $ entirely
    .replace(/₦/g, "NGN ")      // replace ₦ with NGN (jsPDF latin-1 safe)
    .replace(/[^\x00-\xFF]/g, c => {
      // Keep common extended latin, replace anything else
      const map = { "₦":"NGN ", "–":"-", "—":"-", "\u2019":"'", "\u2018":"'", "\u201C":'"', "\u201D":'"' };
      return map[c] ?? "";
    })
    .trim();
}

function naira(amount) {
  if (!amount && amount !== 0) return "";
  return `NGN ${Number(amount).toLocaleString("en-NG")}`;
}

// ── Helpers ───────────────────────────────────────────────────────────
function ts() {
  return new Date().toLocaleString("en-NG", {
    day:"2-digit", month:"short", year:"numeric",
    hour:"2-digit", minute:"2-digit", hour12:true,
  });
}

function watermark(doc, W, H) {
  doc.saveGraphicsState();
  doc.setGState(new doc.GState({ opacity: 0.38 }));
  doc.setFontSize(80);
  doc.setFont("helvetica","bold");
  doc.setTextColor(...C.green);
  doc.text("TerraIQ+", W/2, H/2, { align:"center", angle:35 });
  doc.restoreGraphicsState();
}

function pageHeader(doc, W, title, stamp) {
  doc.setFillColor(...C.green);
  doc.rect(0, 0, W, 22, "F");
  // Logo
  doc.setFontSize(13); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
  doc.text("TerraIQ+", 14, 14);
  // Title
  doc.setFontSize(9); doc.setFont("helvetica","normal");
  doc.text(safe(title), W/2, 14, { align:"center" });
  // Timestamp
  doc.setFontSize(7.5);
  doc.text(stamp, W-14, 14, { align:"right" });
  return 30;
}

function pageFooter(doc, W, H, num) {
  doc.setDrawColor(...C.green); doc.setLineWidth(0.3);
  doc.line(14, H-14, W-14, H-14);
  doc.setFontSize(7); doc.setFont("helvetica","normal"); doc.setTextColor(...C.gray);
  doc.text("Generated by TerraIQ+ · Precision Agriculture for Nigerian Farmers", 14, H-8);
  doc.text(`Page ${num}`, W-14, H-8, { align:"right" });
}

function secHead(doc, x, y, text, W) {
  doc.setFillColor(241,247,244);
  doc.rect(x, y-5, W-x*2, 9, "F");
  doc.setDrawColor(...C.green); doc.setLineWidth(0.6);
  doc.line(x, y-5, x, y+4);
  doc.setFontSize(9); doc.setFont("helvetica","bold"); doc.setTextColor(...C.green);
  doc.text(safe(text), x+4, y);
  return y + 11;
}

function wrap(doc, text, x, y, maxW, lh=5.2) {
  if (!text) return y;
  doc.setFontSize(8); doc.setFont("helvetica","normal"); doc.setTextColor(...C.ink);
  const lines = doc.splitTextToSize(safe(text), maxW);
  doc.text(lines, x, y);
  return y + lines.length * lh;
}

// ── CHART: Horizontal bar chart for soil parameters ───────────────────
function drawBarChart(doc, x, y, params, classifications, W) {
  const chartW = W - x*2;
  const barH   = 8;
  const gap    = 4;
  const labelW = 52;
  const valueW = 26;
  const barAreaW = chartW - labelW - valueW - 6;

  const entries = Object.entries(PCOL).filter(([k]) => {
    const v = params[k];
    return v !== undefined && v !== null && v !== "" && +v !== 0;
  });

  if (!entries.length) return y;

  y = secHead(doc, x, y, "SOIL PARAMETER BAR CHART", W);

  entries.forEach(([key, rgb]) => {
    const cls   = classifications?.[key];
    const val   = params[key];
    const pct   = cls ? (S2P[cls.score] ?? 50) : 50;
    const bRgb  = cls ? levelRgb(cls.level) : C.green;
    const label = PNAME[key] ?? key;
    const unit  = PUNIT[key] ?? "";
    const lv    = cls?.label ?? "";

    // Label
    doc.setFontSize(7.5); doc.setFont("helvetica","bold"); doc.setTextColor(...C.ink);
    doc.text(safe(label), x, y + barH*0.65);

    // Color dot
    doc.setFillColor(...rgb);
    doc.circle(x + labelW - 6, y + barH*0.5, 2, "F");

    // Track
    const bx = x + labelW;
    doc.setFillColor(...C.grayL);
    doc.roundedRect(bx, y+1, barAreaW, barH-2, 1.5, 1.5, "F");

    // Fill
    const fillW = Math.max(4, barAreaW * pct / 100);
    doc.setFillColor(...bRgb);
    doc.roundedRect(bx, y+1, fillW, barH-2, 1.5, 1.5, "F");

    // Value text inside bar
    doc.setFontSize(6.5); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
    if (fillW > 20) doc.text(`${val}${unit}`, bx + fillW/2, y + barH*0.62, { align:"center" });

    // Level badge right side
    const bvx = bx + barAreaW + 3;
    doc.setFillColor(...bRgb);
    doc.roundedRect(bvx, y+1, valueW, barH-2, 1.5, 1.5, "F");
    doc.setFontSize(5.5); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
    doc.text(safe(lv).toUpperCase(), bvx + valueW/2, y + barH*0.65, { align:"center" });

    // Value outside bar if bar too small
    if (fillW <= 20) {
      doc.setFontSize(6.5); doc.setFont("helvetica","normal"); doc.setTextColor(...C.ink);
      doc.text(`${val}${unit}`, bx+2, y + barH*0.65);
    }

    y += barH + gap;
  });

  return y + 4;
}

// ── CHART: Pie chart for soil health composition ──────────────────────
function drawPieChart(doc, cx, cy, r, classifications) {
  const entries = Object.entries(PCOL).filter(([k]) => classifications?.[k]);
  if (!entries.length) return;

  // Each slice = score/total * 360
  const scores = entries.map(([k]) => classifications[k]?.score ?? 2);
  const total  = scores.reduce((a,b) => a+b, 0) || 1;

  let angle = -Math.PI / 2; // start at top

  entries.forEach(([key, rgb], i) => {
    const slice = (scores[i] / total) * Math.PI * 2;
    const end   = angle + slice;
    const mid   = angle + slice / 2;

    // Draw slice using line segments (jsPDF has no native arc fill — simulate with triangle fan)
    const steps = Math.max(8, Math.round(slice * 20));
    doc.setFillColor(...rgb);
    doc.setDrawColor(...C.white);
    doc.setLineWidth(0.5);

    // Build polygon points
    const pts = [[cx, cy]];
    for (let s = 0; s <= steps; s++) {
      const a = angle + (slice * s / steps);
      pts.push([cx + r * Math.cos(a), cy + r * Math.sin(a)]);
    }

    // Draw filled polygon
    doc.lines(
      pts.slice(1).map((p, idx) => {
        const prev = pts[idx];
        return [p[0]-prev[0], p[1]-prev[1]];
      }),
      pts[0][0], pts[0][1], [1,1], "FD"
    );

    // Percentage label inside slice if big enough
    if (slice > 0.35) {
      const lx = cx + (r * 0.62) * Math.cos(mid);
      const ly = cy + (r * 0.62) * Math.sin(mid);
      doc.setFontSize(5.5); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
      doc.text(`${Math.round(scores[i]/total*100)}%`, lx, ly, { align:"center" });
    }

    angle = end;
  });

  // White center circle (donut)
  doc.setFillColor(...C.white);
  doc.circle(cx, cy, r * 0.38, "F");

  // Center label
  doc.setFontSize(6); doc.setFont("helvetica","bold"); doc.setTextColor(...C.green);
  doc.text("SOIL", cx, cy-1, { align:"center" });
  doc.text("HEALTH", cx, cy+4, { align:"center" });
}

// ── CHART: Legend for pie chart ───────────────────────────────────────
function drawPieLegend(doc, x, y, classifications) {
  const entries = Object.entries(PCOL).filter(([k]) => classifications?.[k]);
  entries.forEach(([key, rgb], i) => {
    const cls = classifications[key];
    const ly  = y + i * 9;
    doc.setFillColor(...rgb);
    doc.roundedRect(x, ly-3, 5, 5, 1, 1, "F");
    doc.setFontSize(7); doc.setFont("helvetica","bold"); doc.setTextColor(...C.ink);
    doc.text(safe(PNAME[key]), x+7, ly+1);
    doc.setFont("helvetica","normal"); doc.setTextColor(...C.gray);
    doc.text(safe(cls?.label ?? ""), x+7, ly+5.5);
  });
  return y + entries.length * 9 + 4;
}

// ── CHART: Mini bar chart for scan confidence ─────────────────────────
function drawConfidenceGauge(doc, x, y, confidence, W) {
  const trackW = W - x*2;
  const conf   = Math.min(100, Math.max(0, +confidence || 0));
  const rgb    = conf >= 80 ? C.green : conf >= 60 ? C.amber : C.red;

  doc.setFontSize(8); doc.setFont("helvetica","bold"); doc.setTextColor(...C.ink);
  doc.text(`Identification Confidence: ${conf}%`, x, y);
  y += 4;

  doc.setFillColor(...C.grayL);
  doc.roundedRect(x, y, trackW, 5, 2, 2, "F");
  doc.setFillColor(...rgb);
  doc.roundedRect(x, y, trackW * conf/100, 5, 2, 2, "F");

  // Tick marks at 60% and 80%
  [60, 80].forEach(pct => {
    const tx = x + trackW * pct/100;
    doc.setDrawColor(...C.white); doc.setLineWidth(0.5);
    doc.line(tx, y, tx, y+5);
    doc.setFontSize(5.5); doc.setTextColor(...C.gray);
    doc.text(`${pct}%`, tx, y+9, { align:"center" });
  });

  return y + 14;
}

// ─────────────────────────────────────────────────────────────────────
// SOIL ANALYSIS REPORT
// ─────────────────────────────────────────────────────────────────────
export async function generateSoilReport({ params, result, farmerName, location }) {
  const doc = new jsPDF({ orientation:"portrait", unit:"mm", format:"a4" });
  const W   = doc.internal.pageSize.getWidth();
  const H   = doc.internal.pageSize.getHeight();
  const stamp = ts();
  let y = 0, pageNum = 1;

  const checkY = (need=20) => {
    if (y + need > H - 20) {
      doc.addPage(); pageNum++;
      watermark(doc, W, H);
      pageFooter(doc, W, H, pageNum);
      y = pageHeader(doc, W, "Soil Analysis Report", stamp);
    }
  };

  watermark(doc, W, H);
  pageFooter(doc, W, H, pageNum);
  y = pageHeader(doc, W, "Soil Analysis Report", stamp);

  // ── Info box ─────────────────────────────────────────────────────
  doc.setFillColor(...C.bg);
  doc.roundedRect(14, y, W-28, 22, 3, 3, "F");
  doc.setDrawColor(...C.green); doc.setLineWidth(0.3);
  doc.roundedRect(14, y, W-28, 22, 3, 3, "D");

  doc.setFontSize(8.5); doc.setFont("helvetica","bold"); doc.setTextColor(...C.ink);
  doc.text("Farmer:", 19, y+8);
  doc.setFont("helvetica","normal");
  doc.text(safe(farmerName ?? "TerraIQ+ User"), 40, y+8);
  doc.setFont("helvetica","bold");
  doc.text("Location:", 19, y+15);
  doc.setFont("helvetica","normal");
  doc.text(safe(location ?? "Nigeria"), 42, y+15);
  doc.setFont("helvetica","bold");
  doc.text("Date:", W/2+5, y+8);
  doc.setFont("helvetica","normal");
  doc.text(stamp, W/2+18, y+8);

  // Rating badge
  const rRgb = RATING_RGB[result?.rating] ?? RATING_RGB.fair;
  doc.setFillColor(...rRgb);
  doc.roundedRect(W-52, y+6, 32, 10, 2.5, 2.5, "F");
  doc.setFontSize(9); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
  doc.text(safe(result?.rating ?? "fair").toUpperCase(), W-36, y+13, { align:"center" });
  y += 30;

  // ── Summary ──────────────────────────────────────────────────────
  y = secHead(doc, 14, y, "SOIL HEALTH SUMMARY", W);
  y = wrap(doc, result?.summary, 18, y, W-36);
  y += 5;

  // ── COLOR LEGEND ──────────────────────────────────────────────────
  checkY(22);
  y = secHead(doc, 14, y, "PARAMETER COLOR LEGEND", W);
  const paramKeys = Object.keys(PCOL).filter(k => params?.[k] !== undefined && params?.[k] !== "" && +params?.[k] !== 0);
  const cols3 = Math.ceil(paramKeys.length / 2);
  paramKeys.forEach((key, i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const lx = 18 + col * ((W-36)/2);
    const ly = y + row * 8;
    doc.setFillColor(...PCOL[key]);
    doc.circle(lx, ly-1, 2.2, "F");
    doc.setFontSize(7.5); doc.setFont("helvetica","normal"); doc.setTextColor(...C.ink);
    doc.text(`${PNAME[key]}${PUNIT[key] ? " (" + PUNIT[key] + ")" : ""}`, lx+5, ly);
  });
  y += cols3 * 8 + 4;

  // Status level legend
  const lvLegend = [
    [C.red,    "Critical / Too High"],
    [C.orange, "Low"],
    [C.amber,  "Slightly Elevated"],
    [C.green,  "Sufficient / Optimal"],
  ];
  let lx2 = 18;
  doc.setFontSize(7); doc.setFont("helvetica","italic");
  lvLegend.forEach(([rgb, label]) => {
    doc.setFillColor(...rgb); doc.circle(lx2, y-1, 1.6, "F");
    doc.setTextColor(...C.gray); doc.text(safe(label), lx2+4, y);
    lx2 += 46;
  });
  y += 8;

  // ── BAR CHART ─────────────────────────────────────────────────────
  checkY(80);
  y = drawBarChart(doc, 14, y, params ?? {}, result?.classifications ?? {}, W);

  // ── PIE CHART + LEGEND ────────────────────────────────────────────
  checkY(70);
  y = secHead(doc, 14, y, "SOIL HEALTH COMPOSITION (SCORE-WEIGHTED)", W);

  const cls = result?.classifications ?? {};
  const pieR = 28;
  const pieCX = 14 + pieR + 6;
  const pieCY = y + pieR + 4;

  drawPieChart(doc, pieCX, pieCY, pieR, cls);

  const legendX = pieCX + pieR + 14;
  drawPieLegend(doc, legendX, y + 4, cls);

  y = pieCY + pieR + 10;

  // ── ACTUAL PARAMETER VALUES TABLE ─────────────────────────────────
  checkY(40);
  y = secHead(doc, 14, y, "ACTUAL MEASURED VALUES", W);

  // Table header
  const cols = ["Parameter", "Value", "Unit", "Status", "Optimal Range"];
  const cW   = [(W-28)*0.28, (W-28)*0.14, (W-28)*0.12, (W-28)*0.22, (W-28)*0.24];
  let tx = 14;

  doc.setFillColor(...C.green);
  doc.rect(14, y-4, W-28, 8, "F");
  doc.setFontSize(7); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
  cols.forEach((col, i) => {
    doc.text(safe(col), tx+2, y);
    tx += cW[i];
  });
  y += 5;

  // Table rows — real values with optimal ranges
  const OPTIMAL = {
    nitrogen:       "20–40 mg/kg",
    phosphorus:     "12–30 mg/kg",
    potassium:      "80–180 mg/kg",
    ph:             "5.5–6.8",
    organic_carbon: "1.0–2.5%",
    moisture:       "30–60%",
  };

  Object.entries(PCOL).forEach(([key, rgb], i) => {
    const val = params?.[key];
    if (val === undefined || val === null || val === "" || +val === 0) return;
    const c = cls[key];
    const bRgb = c ? levelRgb(c.level) : C.green;

    // Alternate row bg
    if (i % 2 === 0) {
      doc.setFillColor(245, 250, 247);
      doc.rect(14, y-3.5, W-28, 8, "F");
    }

    tx = 14;
    doc.setFontSize(7); doc.setFont("helvetica","bold"); doc.setTextColor(...rgb);
    doc.text(safe(PNAME[key]), tx+2, y); tx += cW[0];

    doc.setFont("helvetica","bold"); doc.setTextColor(...C.ink);
    doc.text(String(val), tx+2, y); tx += cW[1];

    doc.setFont("helvetica","normal"); doc.setTextColor(...C.gray);
    doc.text(safe(PUNIT[key]), tx+2, y); tx += cW[2];

    // Status badge
    doc.setFillColor(...bRgb);
    doc.roundedRect(tx+1, y-3, cW[3]-4, 6, 1, 1, "F");
    doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
    doc.text(safe(c?.label ?? "").toUpperCase(), tx + (cW[3]-4)/2 + 1, y, { align:"center" });
    tx += cW[3];

    doc.setFont("helvetica","normal"); doc.setTextColor(...C.gray);
    doc.text(safe(OPTIMAL[key] ?? "—"), tx+2, y);

    y += 8;
  });
  y += 4;

  // ── RECOMMENDED CROPS ─────────────────────────────────────────────
  const crops = (result?.best_crops ?? []).map(c => safe(c)).filter(Boolean);
  if (crops.length) {
    checkY(22);
    y = secHead(doc, 14, y, "RECOMMENDED CROPS FOR THIS SOIL", W);
    const perRow = 4;
    crops.forEach((crop, i) => {
      const cx2 = 18 + (i % perRow) * ((W-36)/perRow);
      const cy2 = y + Math.floor(i / perRow) * 9;
      doc.setFillColor(220, 245, 225);
      doc.roundedRect(cx2-2, cy2-4.5, (W-36)/perRow - 2, 7, 2, 2, "F");
      doc.setFontSize(7.5); doc.setFont("helvetica","semibold"); doc.setTextColor(...C.green);
      doc.text(crop, cx2, cy2, { maxWidth: (W-36)/perRow - 4 });
    });
    y += Math.ceil(crops.length / perRow) * 9 + 6;
  }

  // ── FERTILIZER RECOMMENDATIONS ────────────────────────────────────
  const fert = result?.fertilizer_recommendation ?? {};
  const fertItems = [
    { key:"synthetic",   label:"Synthetic Fertilizer",      bg:[255,251,235] },
    { key:"compost",     label:"Allamanda Compost",         bg:[240,253,244] },
    { key:"biochar",     label:"Allamanda Biochar",         bg:[254,243,199] },
    { key:"supplements", label:"Allamanda Soil Supplement", bg:[254,232,232] },
  ];
  if (fertItems.some(f => fert[f.key])) {
    checkY(30);
    y = secHead(doc, 14, y, "FERTILIZER RECOMMENDATIONS", W);
    fertItems.forEach(({ key, label, bg }) => {
      const item = fert[key]; if (!item) return;
      checkY(22);
      doc.setFillColor(...bg);
      doc.roundedRect(14, y, W-28, 20, 2, 2, "F");
      doc.setFontSize(8); doc.setFont("helvetica","bold"); doc.setTextColor(...C.ink);
      doc.text(safe(item.name ?? label), 18, y+7);
      const desc = [item.description, item.benefit, item.benefit_for_this_soil, item.rate && `Rate: ${item.rate}`, item.timing]
        .filter(Boolean).map(safe).join(" · ");
      doc.setFont("helvetica","normal"); doc.setTextColor(...C.gray);
      y = wrap(doc, desc, 18, y+13, W-36);
      y += 4;
    });
  }

  // ── IMPROVEMENT STEPS ─────────────────────────────────────────────
  const steps = result?.improvement_steps ?? [];
  if (steps.length) {
    checkY(30);
    y = secHead(doc, 14, y, "IMPROVEMENT ACTION PLAN", W);
    steps.forEach((step, i) => {
      checkY(14);
      doc.setFillColor(...C.green); doc.circle(20, y-1, 3.5, "F");
      doc.setFontSize(8); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
      doc.text(String(i+1), 20, y, { align:"center" });
      doc.setFont("helvetica","normal"); doc.setTextColor(...C.ink);
      y = wrap(doc, step, 28, y, W-44); y += 3;
    });
  }

  // ── URGENT ACTIONS ────────────────────────────────────────────────
  const urgent = result?.urgent_actions ?? [];
  if (urgent.length) {
    checkY(20);
    y = secHead(doc, 14, y, "URGENT ACTIONS REQUIRED", W);
    doc.setFillColor(254,226,226);
    doc.roundedRect(14, y, W-28, urgent.length*9+6, 2, 2, "F");
    urgent.forEach(action => {
      doc.setFontSize(8); doc.setFont("helvetica","normal"); doc.setTextColor(185,28,28);
      y = wrap(doc, `• ${action}`, 18, y+3, W-36); y += 2;
    });
    y += 4;
  }

  // ── SEASON ADVICE ─────────────────────────────────────────────────
  if (result?.season_advice) {
    checkY(20);
    y = secHead(doc, 14, y, "SEASON PLANTING ADVICE", W);
    y = wrap(doc, result.season_advice, 18, y, W-36); y += 6;
  }

  // ── WEED RISK ─────────────────────────────────────────────────────
  if (result?.weed_risk) {
    checkY(16);
    const wRgb = result.weed_risk==="high" ? C.red : result.weed_risk==="moderate" ? C.amber : C.green;
    doc.setFontSize(8.5); doc.setFont("helvetica","bold"); doc.setTextColor(...C.ink);
    doc.text("Weed Risk:", 14, y);
    doc.setFillColor(...wRgb); doc.roundedRect(40, y-5, 22, 7, 2, 2, "F");
    doc.setFontSize(7); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
    doc.text(safe(result.weed_risk).toUpperCase(), 51, y, { align:"center" });
    y += 6;
    if (result.weed_risk_explanation) {
      y = wrap(doc, result.weed_risk_explanation, 18, y, W-36); y += 4;
    }
  }

  doc.save(`TerraIQ_Soil_Report_${new Date().toISOString().slice(0,10)}.pdf`);
}

// ─────────────────────────────────────────────────────────────────────
// SCAN REPORT
// ─────────────────────────────────────────────────────────────────────
export async function generateScanReport({ result, farmerName, location, imageDataUrl }) {
  const doc = new jsPDF({ orientation:"portrait", unit:"mm", format:"a4" });
  const W   = doc.internal.pageSize.getWidth();
  const H   = doc.internal.pageSize.getHeight();
  const stamp = ts();
  let y = 0, pageNum = 1;

  const checkY = (need=20) => {
    if (y + need > H - 20) {
      doc.addPage(); pageNum++;
      watermark(doc, W, H);
      pageFooter(doc, W, H, pageNum);
      y = pageHeader(doc, W, "Crop Scan Report", stamp);
    }
  };

  watermark(doc, W, H);
  pageFooter(doc, W, H, pageNum);
  y = pageHeader(doc, W, "Crop Scan Report", stamp);

  // ── Info box ─────────────────────────────────────────────────────
  doc.setFillColor(...C.bg);
  doc.roundedRect(14, y, W-28, 18, 3, 3, "F");
  doc.setFontSize(8.5); doc.setFont("helvetica","bold"); doc.setTextColor(...C.ink);
  doc.text("Farmer:", 18, y+7);
  doc.setFont("helvetica","normal"); doc.text(safe(farmerName ?? "TerraIQ+ User"), 40, y+7);
  doc.setFont("helvetica","bold"); doc.text("Location:", 18, y+14);
  doc.setFont("helvetica","normal"); doc.text(safe(location ?? "Nigeria"), 42, y+14);
  doc.setFont("helvetica","bold"); doc.text("Date:", W/2, y+7);
  doc.setFont("helvetica","normal"); doc.text(stamp, W/2+14, y+7);
  y += 24;

  // ── Scan image — proper placement after info box ─────────────────
  if (imageDataUrl) {
    try {
      // Full width image, proportional crop, proper position
      const imgY = y;
      const imgH = 52;
      doc.addImage(imageDataUrl, "JPEG", 14, imgY, W-28, imgH, undefined, "MEDIUM");
      doc.setDrawColor(...C.green); doc.setLineWidth(0.3);
      doc.roundedRect(14, imgY, W-28, imgH, 2, 2, "D");
      // Caption bar at bottom of image
      doc.setFillColor(0, 0, 0, 0.5);
      doc.setFontSize(7); doc.setFont("helvetica","italic"); doc.setTextColor(...C.white);
      doc.text("Scanned plant image", 18, imgY + imgH - 3);
      y += imgH + 6;
    } catch(_) {}
  }

  // ── Identification ────────────────────────────────────────────────
  y = secHead(doc, 14, y, "PLANT IDENTIFICATION", W);
  doc.setFontSize(15); doc.setFont("helvetica","bold"); doc.setTextColor(...C.green);
  doc.text(safe(result?.crop_identified ?? "Unknown Plant"), 18, y);
  y += 6;
  doc.setFontSize(9); doc.setFont("helvetica","italic"); doc.setTextColor(...C.gray);
  doc.text(safe(result?.scientific_name ?? ""), 18, y);
  y += 7;

  // ── Confidence gauge ──────────────────────────────────────────────
  const conf = Math.min(100, Math.max(0, +(result?.identification_confidence ?? result?.confidence ?? 0)));
  y = drawConfidenceGauge(doc, 18, y, conf, W);

  // ── Type + health badges ──────────────────────────────────────────
  let bx = 18;
  if (result?.plant_type) {
    doc.setFillColor(...C.green);
    doc.roundedRect(bx, y-4.5, 30, 7, 2, 2, "F");
    doc.setFontSize(7); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
    doc.text(safe(result.plant_type).toUpperCase(), bx+15, y, { align:"center" }); bx += 34;
  }
  if (result?.is_weed) {
    doc.setFillColor(...C.orange);
    doc.roundedRect(bx, y-4.5, 16, 7, 2, 2, "F");
    doc.setFontSize(7); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
    doc.text("WEED", bx+8, y, { align:"center" }); bx += 20;
  }
  if (result?.is_healthy) {
    doc.setFillColor(...C.green);
    doc.roundedRect(bx, y-4.5, 20, 7, 2, 2, "F");
    doc.setFontSize(7); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
    doc.text("HEALTHY", bx+10, y, { align:"center" });
  }
  y += 10;

  if (result?.identification_notes) {
    doc.setFontSize(7.5); doc.setFont("helvetica","italic"); doc.setTextColor(...C.gray);
    y = wrap(doc, `Visual features: ${result.identification_notes}`, 18, y, W-36); y += 4;
  }

  // ── Diagnosis ─────────────────────────────────────────────────────
  if (!result?.is_healthy && result?.diagnosis) {
    checkY(30);
    y = secHead(doc, 14, y, "DIAGNOSIS", W);
    const sev    = result?.severity ?? "low";
    const sevRgb = SEV_RGB[sev] ?? C.green;

    // Severity bar chart
    const sevLevels = ["low","moderate","high","critical"];
    const sevIdx    = sevLevels.indexOf(sev);
    checkY(20);
    y = secHead(doc, 14, y, "SEVERITY INDICATOR", W);
    const sevW = (W-36) / 4;
    sevLevels.forEach((lv, i) => {
      const sx = 18 + i * sevW;
      const isActive = i <= sevIdx;
      const lvRgb = SEV_RGB[lv] ?? C.green;
      doc.setFillColor(...(isActive ? lvRgb : C.grayL));
      doc.roundedRect(sx, y, sevW-2, 7, 1.5, 1.5, "F");
      doc.setFontSize(6.5); doc.setFont("helvetica","bold");
      doc.setTextColor(isActive ? 255 : 150, isActive ? 255 : 150, isActive ? 255 : 150);
      doc.text(lv.toUpperCase(), sx + (sevW-2)/2, y+4.5, { align:"center" });
    });
    y += 11;

    doc.setFontSize(10); doc.setFont("helvetica","bold"); doc.setTextColor(...C.ink);
    doc.text(safe(result.diagnosis), 18, y); y += 7;

    if (result?.severity_explanation) {
      y = wrap(doc, result.severity_explanation, 18, y, W-36); y += 4;
    }

    if (result?.immediate_action) {
      checkY(18);
      doc.setFillColor(254,243,199);
      doc.roundedRect(14, y, W-28, 14, 2, 2, "F");
      doc.setFontSize(8); doc.setFont("helvetica","bold"); doc.setTextColor(120,53,15);
      doc.text("Immediate Action:", 18, y+6);
      y = wrap(doc, result.immediate_action, 18, y+11, W-36); y += 4;
    }
  }

  // ── Treatment steps ───────────────────────────────────────────────
  const steps = result?.steps ?? [];
  if (steps.length) {
    checkY(20);
    y = secHead(doc, 14, y, "TREATMENT STEPS", W);
    steps.forEach((step, i) => {
      checkY(12);
      doc.setFillColor(...C.green); doc.circle(20, y-1, 3.5, "F");
      doc.setFontSize(8); doc.setFont("helvetica","bold"); doc.setTextColor(...C.white);
      doc.text(String(i+1), 20, y, { align:"center" });
      doc.setFont("helvetica","normal"); doc.setTextColor(...C.ink);
      y = wrap(doc, step, 28, y, W-44); y += 3;
    });
  }

  // ── Local products ────────────────────────────────────────────────
  const products = result?.local_products ?? [];
  if (products.length) {
    checkY(20);
    y = secHead(doc, 14, y, "LOCAL PRODUCTS", W);
    const colW2 = (W-28)/2;
    products.forEach((p, i) => {
      const px2 = 14 + (i%2)*colW2;
      const py2 = y + Math.floor(i/2)*14;
      doc.setFillColor(...C.bg);
      doc.roundedRect(px2+1, py2-1, colW2-4, 12, 2, 2, "F");
      doc.setFontSize(8); doc.setFont("helvetica","bold"); doc.setTextColor(...C.ink);
      doc.text(safe(p.name ?? ""), px2+4, py2+5);
      doc.setFont("helvetica","normal"); doc.setTextColor(...C.green);
      if (p.price_naira) doc.text(naira(p.price_naira), px2+4, py2+10);
      if (p.where) doc.text(safe(p.where), px2+colW2/2, py2+10, { align:"center" });
    });
    y += Math.ceil(products.length/2)*14 + 4;
  }

  // ── Organic option ────────────────────────────────────────────────
  if (result?.organic_option) {
    checkY(18);
    y = secHead(doc, 14, y, "ORGANIC OPTION", W);
    doc.setFillColor(240,253,244);
    doc.roundedRect(14, y, W-28, 16, 2, 2, "F");
    y = wrap(doc, result.organic_option, 18, y+6, W-36); y += 8;
  }

  // ── Prevention ────────────────────────────────────────────────────
  if (result?.prevention) {
    checkY(18);
    y = secHead(doc, 14, y, "PREVENTION", W);
    y = wrap(doc, result.prevention, 18, y, W-36); y += 4;
  }

  // ── Weed action ───────────────────────────────────────────────────
  if (result?.is_weed && result?.weed_action) {
    checkY(18);
    y = secHead(doc, 14, y, "WEED CONTROL", W);
    doc.setFillColor(254,226,226); doc.roundedRect(14, y, W-28, 16, 2, 2, "F");
    doc.setTextColor(185,28,28);
    y = wrap(doc, result.weed_action, 18, y+6, W-36); y += 8;
  }

  doc.save(`TerraIQ_Scan_Report_${new Date().toISOString().slice(0,10)}.pdf`);
}
