import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const en = {
  nav: { dashboard:"Dashboard", scanner:"Crop Scanner", soil:"Soil Analysis", irrigation:"Irrigation", harvest:"Harvest", market:"Market", cooperative:"Cooperative", analytics:"Analytics", profile:"Profile", signout:"Sign Out" },
  dashboard: { greeting:"Good morning", totalScans:"Total Scans", soilTests:"Soil Tests", harvests:"Harvests", recentScans:"Recent Scans", noScans:"No scans yet. Go to Crop Scanner to get started." },
  scanner: { title:"Crop Scanner", subtitle:"Disease, weeds, and pests — identified instantly by AI", useCamera:"Use Camera", uploadPhoto:"Upload Photo from Gallery", tips:"Tips for best results", tip1:"Get close to the affected leaf — fill the frame", tip2:"Good lighting gives better accuracy", tip3:"Show both healthy and affected parts if possible", analysing:"Analysing your crop...", scanAnother:"Scan Another Crop", actNow:"Immediate Action", steps:"Treatment Steps", localProducts:"Local Products", organic:"Organic Option", prevention:"Prevention", confidence:"AI Confidence", healthy:"Plant Looks Healthy", noIssues:"No significant issues detected", retake:"Retake Photo", analyse:"Analyse Crop", healthSummary:"Health Summary", identifiedAs:"Identified As", severityLabel:"Severity", weedDetected:"Weed Detected — Remove", scanReport:"Download PDF Report", feedbackCorrect:"Correct", feedbackWrong:"Wrong — Correct AI", correctionSaved:"Correction saved — AI will learn", noneLabel:"None (Healthy)" },
  soil: { title:"Soil Analysis", subtitle:"Enter your soil test values for AI recommendations", analyse:"Analyse Soil", analysing:"Analysing...", rating:"Soil Health Rating", bestCrops:"Best Crops for This Soil", fertilizer:"Fertilizer Recommendations", synthetic:"Synthetic Fertilizer", compost:"Organic Compost", biochar:"Biochar", supplement:"Soil Supplement", improvement:"How to Improve This Soil", season:"Season Advice", nitrogen:"Nitrogen (mg/kg)", phosphorus:"Phosphorus (mg/kg)", potassium:"Potassium (mg/kg)", ph:"pH Level", moisture:"Moisture (%)", temperature:"Temperature (°C)", targetCrop:"Target crop (optional)" },
  irrigation: { title:"Irrigation Planner", subtitle:"Get a 7-day watering schedule based on your local weather forecast", generate:"Generate 7-Day Plan", generating:"Building plan...", crop:"Crop", farmSize:"Farm size (m²)", soilType:"Soil type", water:"Water", skip:"Skip" },
  harvest: { title:"Harvest Tracker", subtitle:"Log your harvest to get shelf-life predictions", log:"Log Harvest & Predict Shelf Life", logging:"Predicting...", crop:"Crop", quantity:"Quantity (kg)", storage:"Storage method", temperature:"Temperature (°C)", humidity:"Humidity (%)", history:"Harvest History", noHarvests:"No harvests logged yet.", daysLeft:"days left", expired:"Expired" },
  market: { title:"Market Advisor", subtitle:"Find the best market, current prices, and when to sell", getAdvice:"Get Market Advice", getting:"Finding best price...", crop:"Crop", quantity:"Quantity (kg)", quality:"Quality", bestMarket:"Best Market", totalEst:"Total estimate", priceTrend:"Price trend", bestTime:"Best time to sell", negTip:"Negotiation Tip", altMarkets:"Alternative Markets" },
  cooperative: { title:"Cooperative", create:"Create a Cooperative", join:"Join with Invite Code", name:"Cooperative name", region:"Region / State", inviteCode:"Invite code", createBtn:"Create", joinBtn:"Join", alerts:"Cooperative Alerts", noAlerts:"No alerts yet.", members:"members", inviteShare:"Share this" },
  analytics: { title:"Analytics", totalScans:"Total Scans", soilTests:"Soil Tests", harvests:"Harvests", totalHarvest:"Total Harvest", scanActivity:"Scan Activity (14 days)", topDiseases:"Top Diseases Detected", soilPH:"Soil pH Trend", noDisease:"No disease data yet." },
  profile: { title:"Profile & Settings", farmName:"Farm name", state:"State", language:"Language", save:"Save Changes", saving:"Saving...", saved:"Saved", fullName:"Full name" },
  common: { loading:"Loading...", error:"Something went wrong. Try again.", rate:"Rate", where:"Where", benefit:"Benefit", price:"Price", when:"When", recommended:"Recommended", markRead:"Mark all read", noNotifications:"No notifications yet.", historySubtitle:"All your scan and soil records", noData:"None yet", healthy:"Healthy", weed:"Weed", disease:"Disease", confidence:"Confidence", date:"Date", location:"Location", download:"Download PDF Report", share:"Share", viewAll:"View All", back:"Back" },
};

const yo = {
  nav: { dashboard:"Ilé", scanner:"Ẹ̀rọ Ṣàyẹ̀wò", soil:"Ìtúpalẹ̀ Ilẹ̀", irrigation:"Ìpèsè Omi", harvest:"Ìkórè", market:"Ọjà", cooperative:"Àjọ Àgbẹ̀", analytics:"Àpèjúwe", profile:"Profáìlì", signout:"Jáde" },
  dashboard: { greeting:"Ẹ káàárọ̀", totalScans:"Àpapọ̀ Ṣàyẹ̀wò", soilTests:"Ìdánwò Ilẹ̀", harvests:"Ìkórè", recentScans:"Àwọn Ṣàyẹ̀wò Àìpẹ́", noScans:"Kò sí ṣàyẹ̀wò. Lọ sí Ẹ̀rọ Ṣàyẹ̀wò láti bẹ̀rẹ̀." },
  scanner: { title:"Ẹ̀rọ Ṣàyẹ̀wò Irúgbìn", subtitle:"Àrùn, èékanna, àti kòkòrò — mọ̀ lẹ́sẹ̀kẹsẹ̀", useCamera:"Lo Kámẹ́rà", uploadPhoto:"Gbé Àwòrán Sókè", tips:"Àwọn ìmọ̀ràn", tip1:"Súnmọ́ ewé tó ṣàìsàn", tip2:"Ìmọlẹ̀ tó dára fún ìṣẹ̀dá tó péye", tip3:"Fihàn ewé tó dára àti tó bàjẹ́", analysing:"Ń ṣàyẹ̀wò irúgbìn rẹ...", scanAnother:"Ṣàyẹ̀wò Irúgbìn Mìíràn", actNow:"Iṣẹ́ Lẹ́sẹ̀kẹsẹ̀", steps:"Àwọn Ìgbésẹ̀ Ìtọ́jú", localProducts:"Àwọn Ọjà Àdúgbò", organic:"Àṣàyàn Àdánidá", prevention:"Ìdènà", confidence:"Ìgbàgbọ́ AI", healthy:"Irúgbìn Dára", noIssues:"Kò sí ìṣòro tó ṣe pàtàkì", retake:"Ṣe Àwòrán Lẹ́ẹ̀kan Sí", analyse:"Ṣàyẹ̀wò Irúgbìn", healthSummary:"Àkọ́sílẹ̀ Ìlera", identifiedAs:"A Mọ̀ Pé", severityLabel:"Ìpele Àìsàn", weedDetected:"Àgbàdo Àjẹjẹ — Yọ Kúrò", scanReport:"Gbà Ìjábọ̀ PDF", feedbackCorrect:"Tọ̀nà", feedbackWrong:"Àṣìṣe — Ṣàtúnṣe AI", correctionSaved:"Àtúnṣe ti fipamọ́", noneLabel:"Kò sí (Dára)" },
  soil: { title:"Ìtúpalẹ̀ Ilẹ̀", subtitle:"Tẹ àwọn iye ìdánwò ilẹ̀ rẹ fún àwọn ìmọ̀ràn AI", analyse:"Ṣàtúpalẹ̀ Ilẹ̀", analysing:"Ń ṣàtúpalẹ̀...", rating:"Ìpele Ìlera Ilẹ̀", bestCrops:"Àwọn Irúgbìn Tó Dára Jùlọ", fertilizer:"Àwọn Ìdúpẹ́ Ilẹ̀", synthetic:"Ajílẹ̀ Kẹ́míkà", compost:"Ajílẹ̀ Àdánidá", biochar:"Allamanda Biochar", supplement:"Àfikún Ilẹ̀", improvement:"Bí A Ṣe Lè Mú Ilẹ̀ Dára Sí i", season:"Ìmọ̀ràn Àkókò Gbingbin", nitrogen:"Nitrogen (mg/kg)", phosphorus:"Phosphorus (mg/kg)", potassium:"Potassium (mg/kg)", ph:"Ìpele pH", moisture:"Ọ̀rọ̀ Omi (%)", temperature:"Ìgbóná (°C)", targetCrop:"Irúgbìn tó fẹ́ gbin (àṣàyàn)" },
  irrigation: { title:"Ìpèsè Omi", subtitle:"Gba ètò omi ọjọ́ 7 tó dá lórí àsọtẹ́lẹ̀ ọjọ́ ọ̀sán rẹ", generate:"Ṣẹ̀dá Ètò Ọjọ́ 7", generating:"Ń kọ́ ètò...", crop:"Irúgbìn", farmSize:"Ìwọ̀n Oko (m²)", soilType:"Irúkèrèdò Ilẹ̀", water:"Bomi", skip:"Fojú fo" },
  harvest: { title:"Ìtọpa Ìkórè", subtitle:"Ṣètò ìkórè rẹ láti gba àsọtẹ́lẹ̀ ìgbé ayé", log:"Ṣètò Ìkórè & Àsọtẹ́lẹ̀", logging:"Ń ṣàsọtẹ́lẹ̀...", crop:"Irúgbìn", quantity:"Ìpọ̀ (kg)", storage:"Ọ̀nà Ìpamọ́", temperature:"Ìgbóná (°C)", humidity:"Ọ̀rọ̀ Omi (%)", history:"Ìtàn Ìkórè", noHarvests:"Kò sí ìkórè tí a ṣètò.", daysLeft:"ọjọ́ tó kù", expired:"Ó ti pari" },
  market: { title:"Ìmọ̀ràn Ọjà", subtitle:"Rí ọjà tó dára jùlọ, iye owó lọ́wọ́lọ́wọ́", getAdvice:"Gba Ìmọ̀ràn Ọjà", getting:"Ń wá iye tó dára jùlọ...", crop:"Irúgbìn", quantity:"Ìpọ̀ (kg)", quality:"Ìdára", bestMarket:"Ọjà Tó Dára Jùlọ", totalEst:"Àpapọ̀ àbájáde", priceTrend:"Ìṣàn iye owó", bestTime:"Ìgbà tó dára jùlọ láti ta", negTip:"Ìmọ̀ràn Ìdàgbàsókè", altMarkets:"Àwọn Ọjà Mìíràn" },
  cooperative: { title:"Àjọ Àgbẹ̀", create:"Ṣẹ̀dá Àjọ Àgbẹ̀", join:"Darapọ̀ Pẹ̀lú Kóòdù Ìfẹ̀sọ̀nà", name:"Orúkọ Àjọ", region:"Ìpínlẹ̀", inviteCode:"Kóòdù ìfẹ̀sọ̀nà", createBtn:"Ṣẹ̀dá", joinBtn:"Darapọ̀", alerts:"Àwọn Ìkìlọ̀ Àjọ", noAlerts:"Kò sí ìkìlọ̀ sibẹ̀.", members:"ọmọ ẹgbẹ́", inviteShare:"Pín èyí" },
  analytics: { title:"Àpèjúwe", totalScans:"Àpapọ̀ Ṣàyẹ̀wò", soilTests:"Ìdánwò Ilẹ̀", harvests:"Ìkórè", totalHarvest:"Àpapọ̀ Ìkórè", scanActivity:"Iṣẹ́ Ṣàyẹ̀wò (ọjọ́ 14)", topDiseases:"Àwọn Àrùn Tó Ríi Jùlọ", soilPH:"Ìṣàn pH Ilẹ̀", noDisease:"Kò sí data àrùn sibẹ̀." },
  profile: { title:"Profáìlì & Àwọn Ìtòlẹ́sẹẹ̀", farmName:"Orúkọ Oko", state:"Ìpínlẹ̀", language:"Èdè", save:"Fi Àyípadà Pamọ́", saving:"Ń fi pamọ́...", saved:"A fi pamọ́", fullName:"Orúkọ Kíkún" },
  common: { loading:"Ẹ dúró díẹ̀...", error:"Nkankan ló ṣẹ̀. Ẹ tún gbìyànjú.", rate:"Ìwọ̀n", where:"Níbi", benefit:"Àǹfààní", price:"Iye", when:"Ìgbà", recommended:"Ìdánilójú", markRead:"Ṣe gbogbo wọn ni kíkà", noNotifications:"Kò sí ìwífún.", historySubtitle:"Àwọn ìmójútó ìṣàyẹ̀wò àti ilẹ̀ rẹ", noData:"Kò sí sibẹ̀", healthy:"Dára", weed:"Ahún", disease:"Àrùn", confidence:"Ìgbàgbọ́", date:"Ọjọ́", location:"Ibi", download:"Gbà Ìjábọ̀ PDF", share:"Pín", viewAll:"Wo Gbogbo", back:"Padà" },
};

const ha = {
  nav: { dashboard:"Gida", scanner:"Na'urar Bincike", soil:"Nazarin Ƙasa", irrigation:"Ban Ruwa", harvest:"Girbi", market:"Kasuwa", cooperative:"Ƙungiyar Manoma", analytics:"Bayanan Aiki", profile:"Bayanin Kai", signout:"Fita" },
  dashboard: { greeting:"Barka da safe", totalScans:"Jimillar Bincike", soilTests:"Gwajin Ƙasa", harvests:"Girbi", recentScans:"Bincike na Kwanan Nan", noScans:"Babu bincike. Je na'urar bincike don farawa." },
  scanner: { title:"Na'urar Bincike", subtitle:"Cututtuka, ciyawa, da ƙwari — an gane nan take", useCamera:"Yi amfani da Kyamara", uploadPhoto:"Loda Hoto", tips:"Shawarwari", tip1:"Kusanci ganyen da ya yi rashin lafiya", tip2:"Haske mai kyau yana ba da sakamako mafi kyau", tip3:"Nuna ganye mai kyau da na rashin lafiya", analysing:"Ana binciken shuka ka...", scanAnother:"Bincika Wata Shuka", actNow:"Yi Aiki Yanzu", steps:"Matakai na Magani", localProducts:"Kayayyakin Gida", organic:"Zaɓin Halitta", prevention:"Rigakafi", confidence:"Tabbacin AI", healthy:"Shuka Tana da Lafiya", noIssues:"Ba a sami matsala mai muhimmanci", retake:"Ɗauki Hoto Sake", analyse:"Bincika Shuka" },
  soil: { title:"Nazarin Ƙasa", subtitle:"Shigar da darajar gwajin ƙasarka don shawarwarin AI", analyse:"Nazarin Ƙasa", analysing:"Ana nazari...", rating:"Matsayin Lafiyar Ƙasa", bestCrops:"Mafi Kyawun Amfanin Gona", fertilizer:"Shawarwarin Taki", synthetic:"Taki na Sinadarai", compost:"Takin Halitta", biochar:"Allamanda Biochar", supplement:"Ƙarin Abinci na Ƙasa", improvement:"Yadda Za a Inganta Ƙasa", season:"Shawarar Lokacin Shuka", nitrogen:"Nitrogen (mg/kg)", phosphorus:"Phosphorus (mg/kg)", potassium:"Potassium (mg/kg)", ph:"Matsayin pH", moisture:"Danwili (%)", temperature:"Zafi (°C)", targetCrop:"Amfanin gona da ake so (zaɓi)" },
  irrigation: { title:"Tsarin Ban Ruwa", subtitle:"Sami jadawalin ban ruwa na kwana 7", generate:"Ƙirƙiri Tsarin Kwana 7", generating:"Ana gina tsari...", crop:"Amfanin Gona", farmSize:"Girman Gonar (m²)", soilType:"Nau'in Ƙasa", water:"Ba Ruwa", skip:"Tsallake" },
  harvest: { title:"Bibiyar Girbi", subtitle:"Yi rikodin girbi don hasashen tsawon rayuwa", log:"Yi Rikodin Girbi & Hasashe", logging:"Ana hasashe...", crop:"Amfanin Gona", quantity:"Yawa (kg)", storage:"Hanyar Ajiya", temperature:"Zafi (°C)", humidity:"Danwili (%)", history:"Tarihin Girbi", noHarvests:"Babu girbi da aka yi rikodin.", daysLeft:"kwanaki da suka rage", expired:"Ya ƙare" },
  market: { title:"Shawarar Kasuwa", subtitle:"Sami mafi kyawun kasuwa, farashin yanzu", getAdvice:"Sami Shawarar Kasuwa", getting:"Ana neman mafi kyawun farashi...", crop:"Amfanin Gona", quantity:"Yawa (kg)", quality:"Inganci", bestMarket:"Mafi Kyawun Kasuwa", totalEst:"Jimlar hasashe", priceTrend:"Yanayin farashi", bestTime:"Mafi kyawun lokacin siyarwa", negTip:"Shawarar Tattaunawa", altMarkets:"Sauran Kasuwanni" },
  cooperative: { title:"Ƙungiyar Manoma", create:"Ƙirƙiri Ƙungiya", join:"Shiga da Lambar Gayyata", name:"Sunan Ƙungiya", region:"Yanki / Jiha", inviteCode:"Lambar gayyata", createBtn:"Ƙirƙira", joinBtn:"Shiga", alerts:"Faɗakarwar Ƙungiya", noAlerts:"Babu faɗakarwa tukuna.", members:"mambobi", inviteShare:"Raba wannan" },
  analytics: { title:"Bayanan Aiki", totalScans:"Jimillar Bincike", soilTests:"Gwajin Ƙasa", harvests:"Girbi", totalHarvest:"Jimillar Girbi", scanActivity:"Ayyukan Bincike (kwana 14)", topDiseases:"Cututtuka Mafi Yawa", soilPH:"Yanayin pH na Ƙasa", noDisease:"Babu bayanan cuta tukuna." },
  profile: { title:"Bayanin Kai & Saitunan", farmName:"Sunan Gona", state:"Jiha", language:"Harshe", save:"Ajiye Canje-canje", saving:"Ana ajiye...", saved:"An ajiye", fullName:"Cikakken Suna" },
  common: { loading:"Ana jira...", error:"Wani abu ya yi kuskure. Ka sake gwadawa.", rate:"Adadin", where:"Inda", benefit:"Amfani", price:"Farashi", when:"Lokaci", recommended:"Ana Shawartar" },
};

const ig = {
  nav: { dashboard:"Ụlọ", scanner:"Ihe Nyocha", soil:"Nyocha Ala", irrigation:"Ihe Mmiri", harvest:"Ịgbọ Ihe", market:"Ahịa", cooperative:"Otu Ndị Ọrụ", analytics:"Ọnụọgụgụ", profile:"Profaịlụ", signout:"Pụọ" },
  dashboard: { greeting:"Ụtụtụ ọma", totalScans:"Nyocha Niile", soilTests:"Nlele Ala", harvests:"Ịgbọ Ihe", recentScans:"Nyocha Nso Nso a", noScans:"Enweghị nyocha. Gaa na Ihe Nyocha iji malite." },
  scanner: { title:"Ihe Nyocha Ọjị", subtitle:"Ọrịa, ahịhịa ọjọọ, na ụdụ — achọpụtara ngwa ngwa", useCamera:"Jiri Kamara", uploadPhoto:"Bulite Foto", tips:"Ndụmọdụ", tip1:"Bịakwuo ọnụ na akwụkwọ ọjọọ", tip2:"Ìhè ọma na-enye nsonaazụ kacha mma", tip3:"Gosipụta akwụkwọ dị mma na nke ọjọọ", analysing:"Na-enyocha ọjị gị...", scanAnother:"Nyochaa Ọjị Ọzọ", actNow:"Mee Ugbu a", steps:"Nzọụkwụ Ọgwụgwọ", localProducts:"Ngwaọrụ Mpaghara", organic:"Nhọrọ Eke", prevention:"Mgbochi", confidence:"Ntụkwasị Obi AI", healthy:"Ọjị Dị Mma", noIssues:"Achọtaghị nsogbu dị mkpa", retake:"Were Foto Ọzọ", analyse:"Nyochaa Ọjị" },
  soil: { title:"Nyocha Ala", subtitle:"Tinye ụkpụrụ nlele ala gị maka ndụmọdụ AI", analyse:"Nyochaa Ala", analysing:"Na-enyocha...", rating:"Ogo Ahụike Ala", bestCrops:"Ọjị Kachasị Mma maka Ala a", fertilizer:"Ndụmọdụ Nri Ala", synthetic:"Nri Ala Kemịkal", compost:"Nri Ala Eke", biochar:"Allamanda Biochar", supplement:"Mgbakwunye Ala", improvement:"Otu Esi Eme Ala Ka Ọ Dị Mma", season:"Ndụmọdụ Oge Ịkụ Osisi", nitrogen:"Nitrogen (mg/kg)", phosphorus:"Phosphorus (mg/kg)", potassium:"Potassium (mg/kg)", ph:"Ogo pH", moisture:"Mmiri Ala (%)", temperature:"Okpomọkụ (°C)", targetCrop:"Ọjị achọrọ (nhọrọ)" },
  irrigation: { title:"Atụmatụ Mmiri", subtitle:"Nweta usoro ihe mmiri ụbọchị 7", generate:"Mepụta Atụmatụ Ụbọchị 7", generating:"Na-ewu atụmatụ...", crop:"Ọjị", farmSize:"Ogo Ugbo (m²)", soilType:"Ụdị Ala", water:"Tinye Mmiri", skip:"Wụfee" },
  harvest: { title:"Ihe Nyocha Ịgbọ Ihe", subtitle:"Deee ịgbọ ihe gị iji nweta amụma ndụ shelf", log:"Deee Ịgbọ Ihe & Amụma", logging:"Na-amụma...", crop:"Ọjị", quantity:"Ọnụ (kg)", storage:"Usoro Nchekwa", temperature:"Okpomọkụ (°C)", humidity:"Mmiri Ala (%)", history:"Akụkọ Ịgbọ Ihe", noHarvests:"Enweghị ịgbọ ihe e dere.", daysLeft:"ụbọchị fọdụrụ", expired:"Agwụla" },
  market: { title:"Ndụmọdụ Ahịa", subtitle:"Chọta ahịa kachasị mma, ọnụahịa ugbu a", getAdvice:"Nweta Ndụmọdụ Ahịa", getting:"Na-achọ ọnụahịa kacha mma...", crop:"Ọjị", quantity:"Ọnụ (kg)", quality:"Àgwà", bestMarket:"Ahịa Kachasị Mma", totalEst:"Mkpokọta amụma", priceTrend:"Ụkọ ọnụahịa", bestTime:"Oge kachasị mma isi ere", negTip:"Ndụmọdụ Mkparịta Ụka", altMarkets:"Ahịa Ndị Ọzọ" },
  cooperative: { title:"Otu Ndị Ọrụ", create:"Mepụta Otu", join:"Sonye na Koodu Ọnụ Ọnụ", name:"Aha Otu", region:"Mpaghara / Steeti", inviteCode:"Koodu ọnụ ọnụ", createBtn:"Mepụta", joinBtn:"Sonye", alerts:"Ọkwa Otu", noAlerts:"Enweghị ọkwa tochie.", members:"ndị otu", inviteShare:"Kekọrịta nke a" },
  analytics: { title:"Ọnụọgụgụ", totalScans:"Nyocha Niile", soilTests:"Nlele Ala", harvests:"Ịgbọ Ihe", totalHarvest:"Mkpokọta Ịgbọ Ihe", scanActivity:"Ọrụ Nyocha (ụbọchị 14)", topDiseases:"Ọrịa Ndị Kachasị Nọ", soilPH:"Ụkọ pH Ala", noDisease:"Enweghị data ọrịa tochie." },
  profile: { title:"Profaịlụ & Ntọala", farmName:"Aha Ugbo", state:"Steeti", language:"Asụsụ", save:"Chekwaa Mgbanwe", saving:"Na-echekwa...", saved:"Echekwara", fullName:"Aha Zuru Oke" },
  common: { loading:"Na-atọ nche...", error:"Ihe mere. Nwaa ọzọ.", rate:"Ọnụ", where:"Ebe", benefit:"Uru", price:"Ọnụahịa", when:"Mgbe", recommended:"A na-atụ aro" },
};

i18n.use(initReactI18next).init({
  resources: {
    en: { translation: en },
    yo: { translation: yo },
    ha: { translation: ha },
    ig: { translation: ig },
  },
  lng: "en",
  fallbackLng: "en",
  interpolation: { escapeValue: false },
});

export default i18n;
