import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const en = {
  nav: { dashboard:"Dashboard", scanner:"Crop Scanner", soil:"Soil Analysis", irrigation:"Irrigation", harvest:"Harvest", market:"Market", cooperative:"Cooperative", analytics:"Analytics", profile:"Profile", signout:"Sign Out", notifications:"Notifications" },
  dashboard: { greeting:"Good morning", totalScans:"Total Scans", soilTests:"Soil Tests", harvests:"Harvests", recentScans:"Recent Scans", noScans:"No scans yet. Go to Crop Scanner to get started.", welcome:"Welcome to TerraIQ+", setupMessage:"Your farm is set up. Start by scanning a crop or analysing your soil to see AI recommendations.", scanCrop:"Scan a Crop", analyseSoil:"Analyse Soil", irrigation:"Irrigation", marketPrice:"Market Price", emailConfirmed:"Email Confirmed" },
  scanner: { title:"Crop Scanner", subtitle:"Disease, weeds, and pests — identified instantly by AI", useCamera:"Use Camera", uploadPhoto:"Upload Photo from Gallery", tips:"Tips for best results", tip1:"Get close to the affected leaf — fill the frame", tip2:"Good lighting gives better accuracy", tip3:"Show both healthy and affected parts if possible", analysing:"Analysing your crop...", scanAnother:"Scan Another Crop", actNow:"Immediate Action", steps:"Treatment Steps", localProducts:"Local Products", organic:"Organic Option", prevention:"Prevention", confidence:"AI Confidence", healthy:"Plant Looks Healthy", noIssues:"No significant issues detected", retake:"Retake Photo", analyse:"Analyse Crop", healthSummary:"Health Summary", identifiedAs:"Identified As", severityLabel:"Severity", weedDetected:"Weed Detected — Remove", scanReport:"Download PDF Report", feedbackCorrect:"Correct", feedbackWrong:"Wrong — Correct AI", correctionSaved:"Correction saved — AI will learn", noneLabel:"None (Healthy)", addAngle:"Add angle", noPlantFound:"No plant found", scanPhotos:"Scan {count} Photo{plural}", startOver:"Start over", analysingAngles:"ANALYSING {count} ANGLE{plural}", anglesUsed:"Angles used:", lowConfidence:"LOW CONFIDENCE", anglesCount:"{count} ANGLES", confidenceWarning:"⚠ {percent}% confidence — verify this result", confidenceTip:"Tip: try taking a clearer photo of the leaf from directly above or below", weedDetectedTitle:"⚠ Weed Detected", plantHealthy:"Plant looks healthy. No visible disease or pest detected.", scanConfidence:"Scan confidence", immediateAction:"⚡ Immediate Action" },
  soil: { title:"Soil Analysis", subtitle:"Enter your soil test values for AI recommendations", analyse:"Analyse Soil", analysing:"Analysing...", rating:"Soil Health Rating", bestCrops:"Best Crops for This Soil", fertilizer:"Fertilizer Recommendations", synthetic:"Synthetic Fertilizer", compost:"Organic Compost", biochar:"Biochar", supplement:"Soil Supplement", improvement:"How to Improve This Soil", season:"Season Advice", nitrogen:"Nitrogen (mg/kg)", phosphorus:"Phosphorus (mg/kg)", potassium:"Potassium (mg/kg)", ph:"pH Level", moisture:"Moisture (%)", temperature:"Temperature (°C)", targetCrop:"Target crop (optional)", enterAtLeast:"Enter at least Nitrogen and pH", analysingToast:"Analysing your soil...", ratingToast:"Soil rating:" },
  irrigation: { title:"Irrigation Planner", subtitle:"Get a 7-day watering schedule based on your local weather forecast", generate:"Generate 7-Day Plan", generating:"Building plan...", crop:"Crop", farmSize:"Farm size (m²)", soilType:"Soil type", water:"Water", skip:"Skip" },
  harvest: { title:"Harvest Tracker", subtitle:"Log your harvest to get shelf-life predictions", log:"Log Harvest & Predict Shelf Life", logging:"Predicting...", crop:"Crop", quantity:"Quantity (kg)", storage:"Storage method", temperature:"Temperature (°C)", humidity:"Humidity (%)", history:"Harvest History", noHarvests:"No harvests logged yet.", daysLeft:"days left", expired:"Expired" },
  market: { title:"Market Advisor", subtitle:"Find the best market, current prices, and when to sell", getAdvice:"Get Market Advice", getting:"Finding best price...", crop:"Crop", quantity:"Quantity (kg)", quality:"Quality", bestMarket:"Best Market", totalEst:"Total estimate", priceTrend:"Price trend", bestTime:"Best time to sell", negTip:"Negotiation Tip", altMarkets:"Alternative Markets" },
  cooperative: { title:"Cooperative", create:"Create a Cooperative", join:"Join with Invite Code", name:"Cooperative name", region:"Region / State", inviteCode:"Invite code", createBtn:"Create", joinBtn:"Join", alerts:"Cooperative Alerts", noAlerts:"No alerts yet.", members:"members", inviteShare:"Share this" },
  analytics: { title:"Analytics", totalScans:"Total Scans", soilTests:"Soil Tests", harvests:"Harvests", totalHarvest:"Total Harvest", scanActivity:"Scan Activity (14 days)", topDiseases:"Top Diseases Detected", soilPH:"Soil pH Trend", noDisease:"No disease data yet." },
  profile: { title:"Profile & Settings", farmName:"Farm name", state:"State", language:"Language", save:"Save Changes", saving:"Saving...", saved:"Saved", fullName:"Full name", personalDetails:"Personal Details", location:"Location", locationDesc:"Your city gives you local market prices, cooperative discovery, and city-specific advice.", languageDesc:"Tap a language to preview it instantly. Save to make it permanent.", active:"Active" },
  auth: { createAccount:"Create your account", yourDetails:"Your details", fullName:"Full name", email:"Email", password:"Password", min8Chars:"Minimum 8 characters", welcomeBack:"Welcome back to TerraIQ+", signInAccount:"Sign in to your farm account", signIn:"Sign In", noAccount:"Don't have an account? Sign up", forgotPassword:"Forgot password?", enterEmailPassword:"Enter your email and password", show:"Show", continue:"Continue", fillAllFields:"Please fill in all fields" },
  common: { loading:"Loading...", error:"Something went wrong. Try again.", rate:"Rate", where:"Where", benefit:"Benefit", price:"Price", when:"When", recommended:"Recommended", markRead:"Mark all read", noNotifications:"No notifications yet.", historySubtitle:"All your scan and soil records", noData:"None yet", healthy:"Healthy", weed:"Weed", disease:"Disease", confidence:"Confidence", date:"Date", location:"Location", download:"Download PDF Report", share:"Share", viewAll:"View All", back:"Back", setLocation:"Set your location in Profile to see weather", analysingSoilImage:"Analysing soil image...", analysingFarmConditions:"Analysing your farm conditions...", enterAtLeastNitrogen:"Enter at least Total Nitrogen or Organic Carbon", accountCreated:"Account created!", emailConfirmed:"Email confirmed! Welcome to TerraIQ+" },
  empty: { noScans:"No scans yet", noScansSubtitle:"Scan your first crop to detect diseases, weeds, and pests in 5 seconds.", scanCrop:"Scan a Crop", noSoilTests:"No soil tests yet", noSoilTestsSubtitle:"Enter your soil readings to get Allamanda Compost, Biochar, and Supplement recommendations.", analyseSoil:"Analyse Soil", noHarvests:"No harvests logged", noHarvestsSubtitle:"Log your first harvest to get shelf-life predictions and spoilage alerts.", logHarvest:"Log a Harvest", noMarketQueries:"No market queries yet", noMarketQueriesSubtitle:"Enter a crop to find the best market, current Naira prices, and when to sell.", getMarketAdvice:"Get Market Advice", noData:"No data to show yet", noDataSubtitle:"Start scanning crops and logging soil tests. Your analytics will build up here automatically.", scanFirstCrop:"Scan Your First Crop", notInCooperative:"Not in a cooperative yet", notInCooperativeSubtitle:"Create a cooperative for your farming community or join one with an invite code.", noAlerts:"No alerts yet" },
  weather: { today:"Today", tomorrow:"Tomorrow", rain:"rain", heavyRain:"Heavy rain likely — skip irrigation today", lightRain:"Rain possible — check before irrigating", veryHot:"Very hot — water crops early morning only", highHumid:"High humidity — watch for fungal disease", goodDay:"Good conditions for field work today", clearSky:"Clear sky", mainlyClear:"Mainly clear", partlyCloudy:"Partly cloudy", overcast:"Overcast", foggy:"Foggy", lightDrizzle:"Light drizzle", drizzle:"Drizzle", heavyDrizzle:"Heavy drizzle", lightRain:"Light rain", moderateRain:"Moderate rain", heavyRain:"Heavy rain", lightSnow:"Light snow", moderateSnow:"Moderate snow", heavySnow:"Heavy snow", rainShowers:"Rain showers", violentShowers:"Violent showers", thunderstorm:"Thunderstorm" },
};

const yo = {
  nav: { dashboard:"Ilé", scanner:"Ẹ̀rọ Ṣàyẹ̀wò", soil:"Ìtúpalẹ̀ Ilẹ̀", irrigation:"Ìpèsè Omi", harvest:"Ìkórè", market:"Ọjà", cooperative:"Àjọ Àgbẹ̀", analytics:"Àpèjúwe", profile:"Profáìlì", signout:"Jáde", notifications:"Àwọn Ìkìlọ̀" },
  dashboard: { greeting:"Ẹ káàárọ̀", totalScans:"Àpapọ̀ Ṣàyẹ̀wò", soilTests:"Ìdánwò Ilẹ̀", harvests:"Ìkórè", recentScans:"Àwọn Ṣàyẹ̀wò Àìpẹ́", noScans:"Kò sí ṣàyẹ̀wò sibẹ̀. Lọ sí Ẹ̀rọ Ṣàyẹ̀wò láti bẹ̀rẹ̀.", welcome:"Káàbọ̀ sí TerraIQ+", setupMessage:"Oko rẹ ti ṣeto. Bẹ̀rẹ̀ sí ṣàyẹ̀wò irúgbìn tàbí ṣàtúpalẹ̀ ilẹ̀ rẹ láti rí àwọn ìmọ̀ràn AI.", scanCrop:"Ṣàyẹ̀wò Irúgbìn", analyseSoil:"Ṣàtúpalẹ̀ Ilẹ̀", irrigation:"Ìpèsè Omi", marketPrice:"Iye Ọjà", emailConfirmed:"Ìmẹ̀lì Ti Fidi Rẹ̀ Múlẹ̀" },
  scanner: { title:"Ẹ̀rọ Ṣàyẹ̀wò Irúgbìn", subtitle:"Àrùn, èékanna, àti kòkòrò — mọ̀ lẹ́sẹ̀kẹsẹ̀", useCamera:"Lo Kámẹ́rà", uploadPhoto:"Gbé Àwòrán Sókè", tips:"Àwọn ìmọ̀ràn", tip1:"Súnmọ́ ewé tó ṣàìsàn", tip2:"Ìmọlẹ̀ tó dára fún ìṣẹ̀dá tó péye", tip3:"Fihàn ewé tó dára àti tó bàjẹ́", analysing:"Ń ṣàyẹ̀wò irúgbìn rẹ...", scanAnother:"Ṣàyẹ̀wò Irúgbìn Mìíràn", actNow:"Iṣẹ́ Lẹ́sẹ̀kẹsẹ̀", steps:"Àwọn Ìgbésẹ̀ Ìtọ́jú", localProducts:"Àwọn Ọjà Àdúgbò", organic:"Àṣàyàn Àdánidá", prevention:"Ìdènà", confidence:"Ìgbàgbọ́ AI", healthy:"Irúgbìn Dára", noIssues:"Kò sí ìṣòro tó ṣe pàtàkì", retake:"Ṣe Àwòrán Lẹ́ẹ̀kan Sí", analyse:"Ṣàyẹ̀wò Irúgbìn", healthSummary:"Àkọ́sílẹ̀ Ìlera", identifiedAs:"A Mọ̀ Pé", severityLabel:"Ìpele Àìsàn", weedDetected:"Àgbàdo Àjẹjẹ — Yọ Kúrò", scanReport:"Gbà Ìjábọ̀ PDF", feedbackCorrect:"Tọ̀nà", feedbackWrong:"Àṣìṣe — Ṣàtúnṣe AI", correctionSaved:"Àtúnṣe ti fipamọ́", noneLabel:"Kò sí (Dára)", addAngle:"Ṣàfikún ìdúró", noPlantFound:"Kò sí irúgbìn tí a rí", scanPhotos:"Ṣàyẹ̀wò {count} Àwòrán{plural}", startOver:"Bẹ̀rẹ̀ lẹ́ẹ̀kan sí", analysingAngles:"Ń ṢÀYẸ̀WÒ {count} ÌDÚRÓ{plural}", anglesUsed:"Àwọn ìdúró tí a lo:", lowConfidence:"ÌGBÀGBỌ́ KÈRÈ", anglesCount:"{count} Àwọn Ìdúró", confidenceWarning:"⚠ {percent}% ìgbàgbọ́ — ṣàyẹ̀wò àbájáde yìí", confidenceTip:"Ìmọ̀ràn: gbìyànjú láti ya àwòrán tó ṣàfẹ́rẹ̀ ti ewé láti orí tàbí ìsàlẹ̀ tààrà", weedDetectedTitle:"⚠ Àgbàdo Àjẹjẹ", plantHealthy:"Irúgbìn dára. Kò sí àrùn tàbí kòkòrò tí a rí.", scanConfidence:"Ìgbàgbọ́ ìṣàyẹ̀wò", immediateAction:"⚡ Iṣẹ́ Lẹ́sẹ̀kẹsẹ̀" },
  soil: { title:"Ìtúpalẹ̀ Ilẹ̀", subtitle:"Tẹ àwọn iye ìdánwò ilẹ̀ rẹ fún àwọn ìmọ̀ràn AI", analyse:"Ṣàtúpalẹ̀ Ilẹ̀", analysing:"Ń ṣàtúpalẹ̀...", rating:"Ìpele Ìlera Ilẹ̀", bestCrops:"Àwọn Irúgbìn Tó Dára Jùlọ", fertilizer:"Àwọn Ìdúpẹ́ Ilẹ̀", synthetic:"Ajílẹ̀ Kẹ́míkà", compost:"Ajílẹ̀ Àdánidá", biochar:"Allamanda Biochar", supplement:"Àfikún Ilẹ̀", improvement:"Bí A Ṣe Lè Mú Ilẹ̀ Dára Sí i", season:"Ìmọ̀ràn Àkókò Gbingbin", nitrogen:"Nitrogen (mg/kg)", phosphorus:"Phosphorus (mg/kg)", potassium:"Potassium (mg/kg)", ph:"Ìpele pH", moisture:"Ọ̀rọ̀ Omi (%)", temperature:"Ìgbóná (°C)", targetCrop:"Irúgbìn tó fẹ́ gbin (àṣàyàn)", enterAtLeast:"Tẹ o kere Nitrogen àti pH", analysingToast:"Ń ṣàtúpalẹ̀ ilẹ̀ rẹ...", ratingToast:"Ìpele ilẹ̀:" },
  irrigation: { title:"Ìpèsè Omi", subtitle:"Gba ètò omi ọjọ́ 7 tó dá lórí àsọtẹ́lẹ̀ ọjọ́ ọ̀sán rẹ", generate:"Ṣẹ̀dá Ètò Ọjọ́ 7", generating:"Ń kọ́ ètò...", crop:"Irúgbìn", farmSize:"Ìwọ̀n Oko (m²)", soilType:"Irúkèrèdò Ilẹ̀", water:"Bomi", skip:"Fojú fo" },
  harvest: { title:"Ìtọpa Ìkórè", subtitle:"Ṣètò ìkórè rẹ láti gba àsọtẹ́lẹ̀ ìgbé ayé", log:"Ṣètò Ìkórè & Àsọtẹ́lẹ̀", logging:"Ń ṣàsọtẹ́lẹ̀...", crop:"Irúgbìn", quantity:"Ìpọ̀ (kg)", storage:"Ọ̀nà Ìpamọ́", temperature:"Ìgbóná (°C)", humidity:"Ọ̀rọ̀ Omi (%)", history:"Ìtàn Ìkórè", noHarvests:"Kò sí ìkórè tí a ṣètò.", daysLeft:"ọjọ́ tó kù", expired:"Ó ti pari" },
  market: { title:"Ìmọ̀ràn Ọjà", subtitle:"Rí ọjà tó dára jùlọ, iye owó lọ́wọ́lọ́wọ́", getAdvice:"Gba Ìmọ̀ràn Ọjà", getting:"Ń wá iye tó dára jùlọ...", crop:"Irúgbìn", quantity:"Ìpọ̀ (kg)", quality:"Ìdára", bestMarket:"Ọjà Tó Dára Jùlọ", totalEst:"Àpapọ̀ àbájáde", priceTrend:"Ìṣàn iye owó", bestTime:"Ìgbà tó dára jùlọ láti ta", negTip:"Ìmọ̀ràn Ìdàgbàsókè", altMarkets:"Àwọn Ọjà Mìíràn" },
  cooperative: { title:"Àjọ Àgbẹ̀", create:"Ṣẹ̀dá Àjọ Àgbẹ̀", join:"Darapọ̀ Pẹ̀lú Kóòdù Ìfẹ̀sọ̀nà", name:"Orúkọ Àjọ", region:"Ìpínlẹ̀", inviteCode:"Kóòdù ìfẹ̀sọ̀nà", createBtn:"Ṣẹ̀dá", joinBtn:"Darapọ̀", alerts:"Àwọn Ìkìlọ̀ Àjọ", noAlerts:"Kò sí ìkìlọ̀ sibẹ̀.", members:"ọmọ ẹgbẹ́", inviteShare:"Pín èyí" },
  analytics: { title:"Àpèjúwe", totalScans:"Àpapọ̀ Ṣàyẹ̀wò", soilTests:"Ìdánwò Ilẹ̀", harvests:"Ìkórè", totalHarvest:"Àpapọ̀ Ìkórè", scanActivity:"Iṣẹ́ Ṣàyẹ̀wò (ọjọ́ 14)", topDiseases:"Àwọn Àrùn Tó Ríi Jùlọ", soilPH:"Ìṣàn pH Ilẹ̀", noDisease:"Kò sí data àrùn sibẹ̀." },
  profile: { title:"Profáìlì & Àwọn Ìtòlẹ́sẹẹ̀", farmName:"Orúkọ Oko", state:"Ìpínlẹ̀", language:"Èdè", save:"Fi Àyípadà Pamọ́", saving:"Ń fi pamọ́...", saved:"A fi pamọ́", fullName:"Orúkọ Kíkún", personalDetails:"Àwọn Àlàyé Ara Ẹni", location:"Ibi", locationDesc:"Ìlú rẹ fún ọ ní iye owó ọjà àdúgbò, ìwádìì àjọ àgbẹ̀, àti ìmọ̀ràn tí ó dá lórí ìlú.", languageDesc:"Tẹ èdè kan láti wo lẹ́sẹ̀kẹsẹ̀. Fi pamọ́ láti mú un dára.", active:"Ti ṣiṣẹ́" },
  auth: { createAccount:"Ṣẹ̀dá àkọọlẹ̀ rẹ", yourDetails:"Àwọn àlàyé rẹ", fullName:"Orúkọ kíkún", email:"Ìmẹ̀lì", password:"Ọ̀rọ̀ìpamọ́", min8Chars:"O kere ju 8 àwọn àmì", welcomeBack:"Káàbọ̀ sí TerraIQ+", signInAccount:"Wọlé sí àkọọlẹ̀ oko rẹ", signIn:"Wọlé", noAccount:"Kò sí àkọọlẹ̀? Forúkọ sílẹ̀", forgotPassword:"Gbàgbé ọ̀rọ̀ìpamọ́?", enterEmailPassword:"Tẹ ìmẹ̀lì àti ọ̀rọ̀ìpamọ́ rẹ", show:"Fihàn", continue:"Tẹ̀síwájú", fillAllFields:"Jọ̀wọ́ kún gbogbo àwọn ààyè" },
  common: { loading:"Ẹ dúró díẹ̀...", error:"Nkankan ló ṣẹ̀. Ẹ tún gbìyànjú.", rate:"Ìwọ̀n", where:"Níbi", benefit:"Àǹfààní", price:"Iye", when:"Ìgbà", recommended:"Ìdánilójú", markRead:"Ṣe gbogbo wọn ni kíkà", noNotifications:"Kò sí ìwífún.", historySubtitle:"Àwọn ìmójútó ìṣàyẹ̀wò àti ilẹ̀ rẹ", noData:"Kò sí sibẹ̀", healthy:"Dára", weed:"Ahún", disease:"Àrùn", confidence:"Ìgbàgbọ́", date:"Ọjọ́", location:"Ibi", download:"Gbà Ìjábọ̀ PDF", share:"Pín", viewAll:"Wo Gbogbo", back:"Padà", setLocation:"Ṣètọ́ ìbùdó rẹ ní Profáìlì láti rí ìsọfúnni ọjọ́ ọ̀sán", analysingSoilImage:"Ń ṣàyẹ̀wò àwòrán ilẹ̀...", analysingFarmConditions:"Ń ṣàyẹ̀wò àwọn ipò oko rẹ...", enterAtLeastNitrogen:"Tẹ o kere Nitrogen lápapọ̀ tàbí Organic Carbon", accountCreated:"Àkọọlẹ̀ ti ṣẹ̀dá!", emailConfirmed:"Ìmẹ̀lì ti fidi rẹ̀ múlẹ̀! Káàbọ̀ sí TerraIQ+" },
  empty: { noScans:"Kò sí ṣàyẹ̀wò sibẹ̀", noScansSubtitle:"Ṣàyẹ̀wò irúgbìn rẹ àkọ́kọ́ láti rí àrùn, èékanna, àti kòkòrò ní ìṣẹ́jú 5.", scanCrop:"Ṣàyẹ̀wò Irúgbìn", noSoilTests:"Kò sí ìdánwò ilẹ̀ sibẹ̀", noSoilTestsSubtitle:"Tẹ àwọn ìwọ̀n ilẹ̀ rẹ láti gba àwọn ìmọ̀ràn Allamanda Compost, Biochar, àti Supplement.", analyseSoil:"Ṣàtúpalẹ̀ Ilẹ̀", noHarvests:"Kò sí ìkórè tí a ṣètò", noHarvestsSubtitle:"Ṣètò ìkórè rẹ àkọ́kọ́ láti gba àsọtẹ́lẹ̀ ìgbé ayé àti ìkìlọ̀ ìbàjẹ́.", logHarvest:"Ṣètò Ìkórè", noMarketQueries:"Kò sí ìbéèrè ọjà sibẹ̀", noMarketQueriesSubtitle:"Tẹ irúgbìn kan láti rí ọjà tó dára jùlọ, iye owó Naira lọ́wọ́lọ́wọ́, àti ìgbà tá a ó ta.", getMarketAdvice:"Gba Ìmọ̀ràn Ọjà", noData:"Kò sí data láti fihàn sibẹ̀", noDataSubtitle:"Bẹ̀rẹ̀ sí ṣàyẹ̀wò irúgbìn àti ṣèṣètò ìdánwò ilẹ̀. Àwọn àpèjúwe rẹ yóò kọ́ ara rẹ̀ níhìn-ín.", scanFirstCrop:"Ṣàyẹ̀wò Irúgbìn Rẹ Àkọ́kọ́", notInCooperative:"Kò sí nínú àjọ àgbẹ̀ sibẹ̀", notInCooperativeSubtitle:"Ṣẹ̀dá àjọ àgbẹ̀ fún àwùjọ àgbẹ̀ rẹ tàbí darapọ̀ pẹ̀lú kóòdù ìfẹ̀sọ̀nà.", noAlerts:"Kò sí ìkìlọ̀ sibẹ̀" },
  weather: { today:"Òní", tomorrow:"Ọ̀la", rain:"òjò", heavyRain:"Òjò líle wà — má gbẹ́ irúgbìn lónìí", lightRain:"Òjò ṣeéṣe — ṣàyẹ̀wò kí o tó bomi", veryHot:"Oòrùn líle — bomi irúgbìn ní àárọ̀ kíákíá", highHumid:"Ọ̀rọ̀ omi gaan — jẹ́ kí o sọ ojú sí àrùn olu", goodDay:"Ọjọ́ dára fún iṣẹ́ oko lónìí", clearSky:"Ọ̀run ò ní kùkù", mainlyClear:"Ó ṣàfẹ́rẹ̀ mọ́", partlyCloudy:"Kúrúkúrú díẹ̀", overcast:"Kúrúkúrú púpọ̀", foggy:"Ìkùùkù", lightDrizzle:"Ìrì dídán", drizzle:"Ìrì", heavyDrizzle:"Ìrì líle", lightRain:"Òjò dídán", moderateRain:"Òjò déédéé", heavyRain:"Òjò líle", lightSnow:"Yìnyín dídán", moderateSnow:"Yìnyín déédéé", heavySnow:"Yìnyín líle", rainShowers:"Ìrì òjò", violentShowers:"Ìrì líle", thunderstorm:"Ìjì" },
};

const ha = {
  nav: { dashboard:"Gida", scanner:"Na'urar Bincike", soil:"Nazarin Ƙasa", irrigation:"Ban Ruwa", harvest:"Girbi", market:"Kasuwa", cooperative:"Ƙungiyar Manoma", analytics:"Bayanan Aiki", profile:"Bayanin Kai", signout:"Fita", notifications:"Sanarwa" },
  dashboard: { greeting:"Barka da safe", totalScans:"Jimillar Bincike", soilTests:"Gwajin Ƙasa", harvests:"Girbi", recentScans:"Bincike na Kwanan Nan", noScans:"Babu bincike tukuna. Je na'urar bincike don farawa.", welcome:"Barka da zuwa TerraIQ+", setupMessage:"Gonarka ya shirya. Fara binciken amfanin gona ko nazarin ƙasarka don ganin shawarwarin AI.", scanCrop:"Yi Binciken Shuka", analyseSoil:"Nazarin Ƙasa", irrigation:"Ban Ruwa", marketPrice:"Farashin Kasuwa", emailConfirmed:"An tabbatar da imel" },
  scanner: { title:"Na'urar Bincike", subtitle:"Cututtuka, ciyawa, da ƙwari — an gane nan take", useCamera:"Yi amfani da Kyamara", uploadPhoto:"Loda Hoto", tips:"Shawarwari", tip1:"Kusanci ganyen da ya yi rashin lafiya", tip2:"Haske mai kyau yana ba da sakamako mafi kyau", tip3:"Nuna ganye mai kyau da na rashin lafiya", analysing:"Ana binciken shuka ka...", scanAnother:"Bincika Wata Shuka", actNow:"Yi Aiki Yanzu", steps:"Matakai na Magani", localProducts:"Kayayyakin Gida", organic:"Zaɓin Halitta", prevention:"Rigakafi", confidence:"Tabbacin AI", healthy:"Shuka Tana da Lafiya", noIssues:"Ba a sami matsala mai muhimmanci", retake:"Ɗauki Hoto Sake", analyse:"Bincika Shuka", healthSummary:"Bayanin Lafiya", identifiedAs:"An Gane Shi A Matsayin", severityLabel:"Matsayi", weedDetected:"Ciyawa An Gano — Cire", scanReport:"Sauke PDF", feedbackCorrect:"Daidai", feedbackWrong:"Ba daidai — Gyara AI", correctionSaved:"Gyara an ajiye", noneLabel:"Babu (Lafiya)", addAngle:"Ƙara kusurwa", noPlantFound:"Ba a sami shuka", scanPhotos:"Bincika {count} Hoto{plural}", startOver:"Fara sake", analysingAngles:"ANA BINCKE {count} KUSURWA{plural}", anglesUsed:"Kusurwar da aka yi amfani da ita:", lowConfidence:"TABBACI MARA KYAU", anglesCount:"{count} KUSURWORIN", confidenceWarning:"⚠ {percent}% tabbaci — tabbatar da wannan sakamako", confidenceTip:"Shawara: gwada ɗaukar hoto mai tsabta na ganye daga sama ko ƙasa kai tsaye", weedDetectedTitle:"⚠ Ciyawa An Gano", plantHealthy:"Shuka tana da lafiya. Ba a sami cuta ko ƙwari da aka gani.", scanConfidence:"Tabbacin bincike", immediateAction:"⚡ Aiki Nan Take" },
  soil: { title:"Nazarin Ƙasa", subtitle:"Shigar da darajar gwajin ƙasarka don shawarwarin AI", analyse:"Nazarin Ƙasa", analysing:"Ana nazari...", rating:"Matsayin Lafiyar Ƙasa", bestCrops:"Mafi Kyawun Amfanin Gona", fertilizer:"Shawarwarin Taki", synthetic:"Taki na Sinadarai", compost:"Takin Halitta", biochar:"Allamanda Biochar", supplement:"Ƙarin Abinci na Ƙasa", improvement:"Yadda Za a Inganta Ƙasa", season:"Shawarar Lokacin Shuka", nitrogen:"Nitrogen (mg/kg)", phosphorus:"Phosphorus (mg/kg)", potassium:"Potassium (mg/kg)", ph:"Matsayin pH", moisture:"Danwili (%)", temperature:"Zafi (°C)", targetCrop:"Amfanin gona da ake so (zaɓi)", enterAtLeast:"Shigar da aƙalla Nitrogen ko Organic Carbon", analysingToast:"Ana nazarin ƙasarka...", ratingToast:"Matsayin ƙasa:" },
  irrigation: { title:"Tsarin Ban Ruwa", subtitle:"Sami jadawalin ban ruwa na kwana 7", generate:"Ƙirƙiri Tsarin Kwana 7", generating:"Ana gina tsari...", crop:"Amfanin Gona", farmSize:"Girman Gonar (m²)", soilType:"Nau'in Ƙasa", water:"Ba Ruwa", skip:"Tsallake" },
  harvest: { title:"Bibiyar Girbi", subtitle:"Yi rikodin girbi don hasashen tsawon rayuwa", log:"Yi Rikodin Girbi & Hasashe", logging:"Ana hasashe...", crop:"Amfanin Gona", quantity:"Yawa (kg)", storage:"Hanyar Ajiya", temperature:"Zafi (°C)", humidity:"Danwili (%)", history:"Tarihin Girbi", noHarvests:"Babu girbi da aka yi rikodin.", daysLeft:"kwanaki da suka rage", expired:"Ya ƙare" },
  market: { title:"Shawarar Kasuwa", subtitle:"Sami mafi kyawun kasuwa, farashin yanzu", getAdvice:"Sami Shawarar Kasuwa", getting:"Ana neman mafi kyawun farashi...", crop:"Amfanin Gona", quantity:"Yawa (kg)", quality:"Inganci", bestMarket:"Mafi Kyawun Kasuwa", totalEst:"Jimlar hasashe", priceTrend:"Yanayin farashi", bestTime:"Mafi kyawun lokacin siyarwa", negTip:"Shawarar Tattaunawa", altMarkets:"Sauran Kasuwanni" },
  cooperative: { title:"Ƙungiyar Manoma", create:"Ƙirƙiri Ƙungiya", join:"Shiga da Lambar Gayyata", name:"Sunan Ƙungiya", region:"Yanki / Jiha", inviteCode:"Lambar gayyata", createBtn:"Ƙirƙira", joinBtn:"Shiga", alerts:"Faɗakarwar Ƙungiya", noAlerts:"Babu faɗakarwa tukuna.", members:"mambobi", inviteShare:"Raba wannan" },
  analytics: { title:"Bayanan Aiki", totalScans:"Jimillar Bincike", soilTests:"Gwajin Ƙasa", harvests:"Girbi", totalHarvest:"Jimillar Girbi", scanActivity:"Ayyukan Bincike (kwana 14)", topDiseases:"Cututtuka Mafi Yawa", soilPH:"Yanayin pH na Ƙasa", noDisease:"Babu bayanan cuta tukuna." },
  profile: { title:"Bayanin Kai & Saitunan", farmName:"Sunan Gona", state:"Jiha", language:"Harshe", save:"Ajiye Canje-canje", saving:"Ana ajiye...", saved:"An ajiye", fullName:"Cikakken Suna", personalDetails:"Bayanin Kai", location:"Wuri", locationDesc:"Birninka yana ba ka farashin kasuwa na gida, ganowar ƙungiya, da shawara ta musamman ga birni.", languageDesc:"Danna harshe don ganin shi nan take. Ajiye don sanya shi dindindin.", active:"Aiki" },
  auth: { createAccount:"Ƙirƙiri asusunka", yourDetails:"Bayaninka", fullName:"Cikakken suna", email:"Imel", password:"Kalmar wucewa", min8Chars:"Ƙalla haruffa 8", welcomeBack:"Barka da dawowa zuwa TerraIQ+", signInAccount:"Shiga cikin asusun gonarka", signIn:"Shiga", noAccount:"Babu asusu? Yi rajista", forgotPassword:"Manta kalmar wucewa?", enterEmailPassword:"Shigar da imel da kalmar wucewa", show:"Nuna", continue:"Ci gaba", fillAllFields:"Don Allah cika duk filayen" },
  common: { loading:"Ana jira...", error:"Wani abu ya yi kuskure. Ka sake gwadawa.", rate:"Adadin", where:"Inda", benefit:"Amfani", price:"Farashi", when:"Lokaci", recommended:"Ana Shawartar", markRead:"Nuna an karanta duka", noNotifications:"Babu sanarwa tukuna.", historySubtitle:"Duk bayanan bincike da ƙasa ranka", noData:"Babu tukuna", healthy:"Lafiya", weed:"Ciyawa", disease:"Cuta", confidence:"Tabbaci", date:"Kwanan wata", location:"Wuri", download:"Sauke PDF", share:"Raba", viewAll:"Duba Duka", back:"Koma", setLocation:"Saita wurinka a Bayanin Kai don ganin yanayi", analysingSoilImage:"Ana nazarin hoton ƙasa...", analysingFarmConditions:"Ana nazarin yanayin gonarka...", enterAtLeastNitrogen:"Shigar da aƙalla Nitrogen ko Organic Carbon", accountCreated:"An ƙirƙiri asusu!", emailConfirmed:"An tabbatar da imel! Barka da zuwa TerraIQ+" },
  empty: { noScans:"Babu bincike tukuna", noScansSubtitle:"Yi binciken shuka ka ta farko don gano cututtuka, ciyawa, da ƙwari a cikin dakika 5.", scanCrop:"Yi Binciken Shuka", noSoilTests:"Babu gwajin ƙasa tukuna", noSoilTestsSubtitle:"Shigar da karatun ƙasarka don samun shawarwarin Allamanda Compost, Biochar, da Supplement.", analyseSoil:"Nazarin Ƙasa", noHarvests:"Babu girbi da aka yi rikodin", noHarvestsSubtitle:"Yi rikodin girbi ka ta farko don samun hasashen tsawon rayuwa da faɗakarwar lalacewa.", logHarvest:"Yi Rikodin Girbi", noMarketQueries:"Babu tambayoyin kasuwa tukuna", noMarketQueriesSubtitle:"Shigar da amfanin gona don samun mafi kyawun kasuwa, farashin Naira na yanzu, da lokacin siyarwa.", getMarketAdvice:"Sami Shawarar Kasuwa", noData:"Babu bayanai don nuna tukuna", noDataSubtitle:"Fara binciken amfanin gona da yin rikodin gwajin ƙasa. Bayananka za su ƙara nan ta atomatik.", scanFirstCrop:"Yi Binciken Shuka Ka Ta Farko", notInCooperative:"Babu cikin ƙungiya tukuna", notInCooperativeSubtitle:"Ƙirƙiri ƙungiya don al'ummar manoma ta ku ko shiga tare da lambar gayyata.", noAlerts:"Babu faɗakarwa tukuna" },
  weather: { today:"Yau", tomorrow:"Gobe", rain:"ruwa", heavyRain:"Ruwan sama mai yawa — kar a yi ban ruwa yau", lightRain:"Ruwa yana yiwuwa — duba kafin ban ruwa", veryHot:"Zafi sosai — ba wa amfanin gona ruwa da sassafe", highHumid:"Danshi mai yawa — lura da cututtukan naman gwari", goodDay:"Yanayi mai kyau don aiki a gona yau", clearSky:"Sararin sama mai tsabta", mainlyClear:"Mai tsabta", partlyCloudy:"Gajeren gajere", overcast:"Cike da gajere", foggy:"Hazo", lightDrizzle:"Ruwan sama mai sauki", drizzle:"Ruwan sama", heavyDrizzle:"Ruwan sama mai yawa", lightRain:"Ruwan sama mai sauki", moderateRain:"Ruwan sama matsakaici", heavyRain:"Ruwan sama mai yawa", lightSnow:"Dumin kankara mai sauki", moderateSnow:"Dumin kankara matsakaici", heavySnow:"Dumin kankara mai yawa", rainShowers:"Ruwan sama", violentShowers:"Ruwan sama mai karfi", thunderstorm:"Guguwar aradu" },
};

const ig = {
  nav: { dashboard:"Ụlọ", scanner:"Ihe Nyocha", soil:"Nyocha Ala", irrigation:"Ihe Mmiri", harvest:"Ịgbọ Ihe", market:"Ahịa", cooperative:"Otu Ndị Ọrụ", analytics:"Ọnụọgụgụ", profile:"Profaịlụ", signout:"Pụọ", notifications:"Ọkwa" },
  dashboard: { greeting:"Ụtụtụ ọma", totalScans:"Nyocha Niile", soilTests:"Nlele Ala", harvests:"Ịgbọ Ihe", recentScans:"Nyocha Nso Nso a", noScans:"Enweghị nyocha. Gaa na Ihe Nyocha iji malite.", welcome:"Nnọọ na TerraIQ+", setupMessage:"Emeela ụlọ ọrụ gị. Malite site na nyocha ọjị ma ọ bụ nyocha ala gị iji hụ ndụmọdụ AI.", scanCrop:"Nyochaa Ọjị", analyseSoil:"Nyochaa Ala", irrigation:"Mmiri Ọrụ", marketPrice:"Ọnụahịa Ahịa", emailConfirmed:"Ekwenyere Email" },
  scanner: { title:"Ihe Nyocha Ọjị", subtitle:"Ọrịa, ahịhịa ọjọọ, na ụdụ — achọpụtara ngwa ngwa", useCamera:"Jiri Kamara", uploadPhoto:"Bulite Foto", tips:"Ndụmọdụ", tip1:"Bịakwuo ọnụ na akwụkwọ ọjọọ", tip2:"Ìhè ọma na-enye nsonaazụ kacha mma", tip3:"Gosipụta akwụkwọ dị mma na nke ọjọọ", analysing:"Na-enyocha ọjị gị...", scanAnother:"Nyochaa Ọjị Ọzọ", actNow:"Mee Ugbu a", steps:"Nzọụkwụ Ọgwụgwọ", localProducts:"Ngwaọrụ Mpaghara", organic:"Nhọrọ Eke", prevention:"Mgbochi", confidence:"Ntụkwasị Obi AI", healthy:"Ọjị Dị Mma", noIssues:"Achọtaghị nsogbu dị mkpa", retake:"Were Foto Ọzọ", analyse:"Nyochaa Ọjị", healthSummary:"Nchịkọta Ahụike", identifiedAs:"Achọpụtara Dịka", severityLabel:"Ogo Ọrịa", weedDetected:"Achọpụtara Ahịhịa Ọjọọ — Wepụ", scanReport:"Budata PDF", feedbackCorrect:"Ziri Ezi", feedbackWrong:"Ezighi Ezi — Dozie AI", correctionSaved:"Echekwara mgbazi", noneLabel:"Ọ dịghị (Dị Mma)", addAngle:"Tinye akụkụ", noPlantFound:"Achọtaghị osisi", scanPhotos:"Nyochaa {count} Foto{plural}", startOver:"Malite Ọzọ", analysingAngles:"NA-ENYOCHA {count} AKỤKỤ{plural}", anglesUsed:"Akụkụ ejiri:", lowConfidence:"NTỤKWASỊ OBI ADỊGHỊ", anglesCount:"{count} AKỤKỤ", confidenceWarning:"⚠ {percent}% ntụkwasị obi — nyochaa nsonaazụ a", confidenceTip:"Ndụmọdụ: nwaa ịse foto doro anya nke akwụkwọ site n'elu ma ọ bụ n'okpuru ozugbo", weedDetectedTitle:"⚠ Achọpụtara Ahịhịa Ọjọọ", plantHealthy:"Ọjị dị mma. Achọtaghị ọrịa ma ọ bụ ụdụ a hụrụ.", scanConfidence:"Ntụkwasị obi nnyocha", immediateAction:"⚡ Mme Ugbu a" },
  soil: { title:"Nyocha Ala", subtitle:"Tinye ụkpụrụ nlele ala gị maka ndụmọdụ AI", analyse:"Nyochaa Ala", analysing:"Na-enyocha...", rating:"Ogo Ahụike Ala", bestCrops:"Ọjị Kachasị Mma maka Ala a", fertilizer:"Ndụmọdụ Nri Ala", synthetic:"Nri Ala Kemịkal", compost:"Nri Ala Eke", biochar:"Allamanda Biochar", supplement:"Mgbakwunye Ala", improvement:"Otu Esi Eme Ala Ka Ọ Dị Mma", season:"Ndụmọdụ Oge Ịkụ Osisi", nitrogen:"Nitrogen (mg/kg)", phosphorus:"Phosphorus (mg/kg)", potassium:"Potassium (mg/kg)", ph:"Ogo pH", moisture:"Mmiri Ala (%)", temperature:"Okpomọkụ (°C)", targetCrop:"Ọjị achọrọ (nhọrọ)", enterAtLeast:"Tinye opekempe Nitrogen na pH", analysingToast:"Na-enyocha ala gị...", ratingToast:"Ogo ala:" },
  irrigation: { title:"Atụmatụ Mmiri", subtitle:"Nweta usoro ihe mmiri ụbọchị 7", generate:"Mepụta Atụmatụ Ụbọchị 7", generating:"Na-ewu atụmatụ...", crop:"Ọjị", farmSize:"Ogo Ugbo (m²)", soilType:"Ụdị Ala", water:"Tinye Mmiri", skip:"Wụfee" },
  harvest: { title:"Ihe Nyocha Ịgbọ Ihe", subtitle:"Deee ịgbọ ihe gị iji nweta amụma ndụ shelf", log:"Deee Ịgbọ Ihe & Amụma", logging:"Na-amụma...", crop:"Ọjị", quantity:"Ọnụ (kg)", storage:"Usoro Nchekwa", temperature:"Okpomọkụ (°C)", humidity:"Mmiri Ala (%)", history:"Akụkọ Ịgbọ Ihe", noHarvests:"Enweghị ịgbọ ihe e dere.", daysLeft:"ụbọchị fọdụrụ", expired:"Agwụla" },
  market: { title:"Ndụmọdụ Ahịa", subtitle:"Chọta ahịa kachasị mma, ọnụahịa ugbu a", getAdvice:"Nweta Ndụmọdụ Ahịa", getting:"Na-achọ ọnụahịa kacha mma...", crop:"Ọjị", quantity:"Ọnụ (kg)", quality:"Àgwà", bestMarket:"Ahịa Kachasị Mma", totalEst:"Mkpokọta amụma", priceTrend:"Ụkọ ọnụahịa", bestTime:"Oge kachasị mma isi ere", negTip:"Ndụmọdụ Mkparịta Ụka", altMarkets:"Ahịa Ndị Ọzọ" },
  cooperative: { title:"Otu Ndị Ọrụ", create:"Mepụta Otu", join:"Sonye na Koodu Ọnụ Ọnụ", name:"Aha Otu", region:"Mpaghara / Steeti", inviteCode:"Koodu ọnụ ọnụ", createBtn:"Mepụta", joinBtn:"Sonye", alerts:"Ọkwa Otu", noAlerts:"Enweghị ọkwa tochie.", members:"ndị otu", inviteShare:"Kekọrịta nke a" },
  analytics: { title:"Ọnụọgụgụ", totalScans:"Nyocha Niile", soilTests:"Nlele Ala", harvests:"Ịgbọ Ihe", totalHarvest:"Mkpokọta Ịgbọ Ihe", scanActivity:"Ọrụ Nyocha (ụbọchị 14)", topDiseases:"Ọrịa Ndị Kachasị Nọ", soilPH:"Ụkọ pH Ala", noDisease:"Enweghị data ọrịa tochie." },
  profile: { title:"Profaịlụ & Ntọala", farmName:"Aha Ugbo", state:"Steeti", language:"Asụsụ", save:"Chekwaa Mgbanwe", saving:"Na-echekwa...", saved:"Echekwara", fullName:"Aha Zuru Oke", personalDetails:"Ozi onwe", location:"Ebe", locationDesc:"Obodo gị na-enye gị ọnụahịa ahịa mpaghara, nchọpụta nkwado, na ndụmọdụ kpọmkwem obodo.", languageDesc:"Pịa asụsụ iji hụ ya ozugbo. Chekwaa ka ọ bụrụ nke na-adịgide.", active:"Na-arụ ọrụ" },
  auth: { createAccount:"Mepụta akaụntụ gị", yourDetails:"Ozi gị", fullName:"Aha zuru oke", email:"Email", password:"Okwuntughe", min8Chars:"Opekempe mkpụrụedemede 8", welcomeBack:"Nnọọ na TerraIQ+", signInAccount:"Banye na akaụntụ ugbo gị", signIn:"Banye", noAccount:"Enweghị akaụntụ? Debanye aha", forgotPassword:"Chefuru okwuntughe?", enterEmailPassword:"Tinye email na okwuntughe gị", show:"Gosi", continue:"Gaa n'ihu", fillAllFields:"Biko jupụta mpaghara niile" },
  common: { loading:"Na-atọ nche...", error:"Ihe mere. Nwaa ọzọ.", rate:"Ọnụ", where:"Ebe", benefit:"Uru", price:"Ọnụahịa", when:"Mgbe", recommended:"A na-atụ aro", markRead:"Mee ha niile ka edere", noNotifications:"Enweghị ọkwa tochie.", historySubtitle:"Akụkọ nyocha na ala gị niile", noData:"Enweghị tochie", healthy:"Dị Mma", weed:"Ahịhịa Ọjọọ", disease:"Ọrịa", confidence:"Ntụkwasị Obi", date:"Ụbọchị", location:"Ebe", download:"Budata PDF", share:"Kekọrịta", viewAll:"Hụ Ha Niile", back:"Laghachi", setLocation:"Tọọ ebe i nọ na Profaịlụ iji hụ ihe ọ bụ oge", analysingSoilImage:"Na-enyocha foto ala...", analysingFarmConditions:"Na-enyocha ọnọdụ ugbo gị...", enterAtLeastNitrogen:"Tinye opekempe Nitrogen niile ma ọ bụ Organic Carbon", accountCreated:"E mepụtara akaụntụ!", emailConfirmed:"Ekwenyere email! Nnọọ na TerraIQ+" },
  weather: { today:"Taa", tomorrow:"Echi", rain:"mmiri ozuzo", heavyRain:"Mmiri ozuzo ọnụ — hapụ ihe mmiri taa", lightRain:"Mmiri ozuzo nwere ike isi — lelee tupu itinye mmiri", veryHot:"Ọkụ nke ukwuu — tinye mmiri ọjị n'ụtụtụ", highHumid:"Mmiri n'ikuku dị nnọọ — lekọọ anya maka ọrịa olu", goodDay:"Oge ọma maka ọrụ ugbo taa", clearSky:"Igwe na-egbuke egbuke", mainlyClear:"Na-egbuke egbuke", partlyCloudy:"Na-ekpuchi obere", overcast:"Na-ekpuchi nnọọ", foggy:"Na-ekpuchi", lightDrizzle:"Mmiri ozuzo dị obere", drizzle:"Mmiri ozuzo", heavyDrizzle:"Mmiri ozuzo dị nnọọ", lightRain:"Mmiri ozuzo dị obere", moderateRain:"Mmiri ozuzo dị n'etiti", heavyRain:"Mmiri ozuzo dị nnọọ", lightSnow:"Snow dị obere", moderateSnow:"Snow dị n'etiti", heavySnow:"Snow dị nnọọ", rainShowers:"Mmiri ozuzo", violentShowers:"Mmiri ozuzo dị nnọọ", thunderstorm:"Egwu mmiri" },
};

i18n.use(initReactI18next).init({
  resources: {
    en: { translation: en },
    yo: { translation: yo },
    ha: { translation: ha },
    ig: { translation: ig },
  },
  lng: "en",
  fallbackLng: "en",
  interpolation: { escapeValue: false },
});

export default i18n;
